### ISSUE TITLE
Segmentation fault (core dumped), Intel Aero

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#4491] opened 2017-01-31 14:42 UTC
@dogmaphobic I regularly get a ```Segmentation fault (core dumped), Intel Aero``` when I'm connect to the ```Intel Aero```.
Here's the output of the terminal
![qgc_dump](https://cloud.githubusercontent.com/assets/14769636/22469313/dbd522ea-e7cb-11e6-909f-2155e9294c16.png)
![qgc_dump2](https://cloud.githubusercontent.com/assets/14769636/22469317/ddd54b6a-e7cb-11e6-98fe-9dd00ea78770.png)

**Comment by DonLakeFlyer** [comment] 2017-01-31 23:19
If you aren't running either Master or very latest Stable first step is to run with that.

**Comment by ChristophTobler** [comment] 2017-02-01 05:57
@DonLakeFlyer Sorry for not mentioning... I'm running master that is maybe a week old. But I can try with the very latest

**Comment by DonLakeFlyer** [comment] 2017-02-01 23:48
That should be new enough.

**Comment by DonLakeFlyer** [comment] 2017-02-02 00:25
@ChristophTobler Do you have the ability to build QGC yourself? I don't have one of these boards so repro for me is tricky.

**Comment by DonLakeFlyer** [comment] 2017-02-02 00:36
Also can you run with --logging:full on the command line. Capture output and post. That may help.

**Comment by Victry69** [comment] 2017-02-02 04:11
ok @DonLakeFlyer  
 Hope this will help   If you need anything else  just let me know  .i'll do my best to find the logs in my Mac  ✌🏾

[log.txt](https://github.com/mavlink/qgroundcontrol/files/746798/log.txt)

![screen shot 2017-02-01 at 11 06 21 pm]

(https://cloud.githubusercontent.com/assets/6749950/22536826/128db948-e8d3-11e6-8c4c-0cfe25799bf4.png)

[Process:               QGroundControl [1296].pdf](https://github.com/mavlink/qgroundcontrol/files/746795/Process.QGroundControl.1296.pdf)

**Comment by Victry69** [comment] 2017-02-02 04:18
here's a different  format  ✌🏾 hope it helps 


[Date:Time:       2017-01-30 18:58:26 -0500.pdf](https://github.com/mavlink/qgroundcontrol/files/746809/Date.Time.2017-01-30.18.58.26.-0500.pdf)

**Comment by ChristophTobler** [comment] 2017-02-02 09:29
@DonLakeFlyer here's the output of QGC with ```logging:full``` http://pasted.co/eb3cbf4f

**Comment by DonLakeFlyer** [comment] 2017-02-15 22:22
@NaterGator @dagar Windows builds are still set up to store symbols and debug crashes isn't it?

**Comment by dagar** [comment] 2017-02-15 22:33
We're uploading symbols to s3, but I'm not sure what needs to be done with a windows symbol server to actually use them.

@NaterGator?

**Comment by DonLakeFlyer** [comment] 2017-02-15 22:36
Actually I have a stack trace included here and now that I look at that a stack trace on a different OS isn't going to help. It's deep in Qt Qml code which nevers tells you anything about what is really going on since it's all script processing.

Is there anyone from Intel that could lend/give me one of these boards to test with?

**Comment by dagar** [comment] 2017-02-15 22:41
@ChristophTobler how reproducible is this? Is it always happening at the end of param sync? Has it ever worked?

**Comment by NaterGator** [comment] 2017-02-15 22:49
Yes, windows builds are still storing debugging symbols. The only tricky thing is running pepto to act as a proxy, details are here: https://github.com/mavlink/qgroundcontrol/pull/2680#issuecomment-180029843

Obviously you also need a crash dmp file from a windows user.

**Comment by DonLakeFlyer** [comment] 2017-05-25 22:29
Removing this from gating 3.2 release. Can't do much without a board to test.

**Comment by julianoes** [comment] 2024-10-15 00:27
Just stumbled on this, clearly outdated, so closing.

**Closed by julianoes** 2024-10-15 00:27 UTC
