### ISSUE TITLE
Simulator / Flight Mode Assignments (Naming?) discrepances 

### ISSUE THREAD

**Issue by GervaisK** [mavlink/qgroundcontrol#2969] opened 2016-03-07 23:14 UTC
Users are confused, that chosen e.g. Stabilize is shown as Manual in the headline and sts. not. There´s a discrepancy between simulation and shown (assigned) FM. Other Examples:

Going to Flight Mode Page, it says MANUAL.

![fm1](https://cloud.githubusercontent.com/assets/17418003/13586465/566d9ff0-e4c1-11e5-8b42-6a0d6adb84c0.jpg)

Changing to ACRO it shows ACRO as well in the headline.

![fm2](https://cloud.githubusercontent.com/assets/17418003/13586494/89fc5adc-e4c1-11e5-9c09-712a85e03370.jpg)

Switching back to MANUAL, it shows STABILIZED in the headline

![fm3](https://cloud.githubusercontent.com/assets/17418003/13586498/96495db2-e4c1-11e5-988c-959064522a2c.jpg)

Switching from FLIGHT MODE 1 ACRO to FLIGHT MODE  4 ACRO it shows  MANUAL in the headline again. 

![fm4](https://cloud.githubusercontent.com/assets/17418003/13586500/9e75c1e2-e4c1-11e5-8f2f-4f5ac29c7b82.jpg)

Switching from FLIGHT MODE 1 ACRO to FLIGHT MODE  5 ACRO the headline shows ACRO again.

![fm5](https://cloud.githubusercontent.com/assets/17418003/13586509/a5398f72-e4c1-11e5-94dc-82b6103f365f.jpg)

**Comment by sn0west** [comment] 2016-03-09 16:02
I've been flying today, and there is a big problem with FM 1, 4 and 5!!! The do not take the assigned FM but take the last one that was active! This ist quite dangerous.

I did some tests and my trusted FM where 2 and 3. Unfortunaly I don't have a Log because it wont let me arme if I active the log. This is another Problem, wich I need to check before writing an Issue.

**Comment by GervaisK** [comment] 2016-03-09 16:28
This issue is not solved yet. Please don´t fly, till it is working on your desk.

**Comment by DonLakeFlyer** [comment] 2016-03-09 17:31
I checked that the parameters are being set correctly by QGC. Other than that QGC has no responsibility for changing the actual flight modes. So if this isn't workint correctly while flying it is a firmware side problem.

@LorenzMeier FYI

**Comment by sn0west** [comment] 2016-03-09 18:04
I was aware of this problem due to qgc not changing the mode in the top menue, as it is on the screenshots. So thats why I went flying and noticed this same behaviour during the flight. 
It wasn't dangerous for me because the kill switch works fine as well ;)

**Comment by LorenzMeier** [comment] 2016-03-13 17:55
@sn0west I've fixed the mapping on master now. Could you do a bench test to verify it works for you now?

**Comment by LorenzMeier** [comment] 2016-03-13 17:55
@GervaisK Closing this since fixed.

**Comment by sn0west** [comment] 2016-03-15 06:45
Oh I missed that answer, sorry @LorenzMeier. I will do a test tomorrow evening! Thanks for fixing it anyway.

**Comment by sn0west** [comment] 2016-04-11 21:07
Sorry for the late reply, but it still dosn't work!
On the following screenshots, you see the problems, FM2 is active but in the menue bar it display FM3. So What FM is now active?

I noticed some similar problem but they may have a relation to that problem

![bildschirmfoto 2016-04-11 um 23 00 59](https://cloud.githubusercontent.com/assets/9918649/14442440/118966a0-003a-11e6-8a3c-6f2ed85ad7b6.png)
![bildschirmfoto 2016-04-11 um 23 01 21](https://cloud.githubusercontent.com/assets/9918649/14442439/11894c56-003a-11e6-92b6-6880e716eced.png)
![bildschirmfoto 2016-04-11 um 23 03 06](https://cloud.githubusercontent.com/assets/9918649/14442441/118b3ae8-003a-11e6-8fbb-c3aeb531496d.png)
![bildschirmfoto 2016-04-11 um 23 03 43](https://cloud.githubusercontent.com/assets/9918649/14442442/118fb910-003a-11e6-8896-2ef5db9e5cce.png)

**Comment by DonLakeFlyer** [comment] 2016-04-11 21:24
The flight mode setup screen simulates flight mode seletion according the RC values, not according to the mode the Vehicle is actually in. This allows you to test you trasmitter settings while you are disarmed and not flying.

Whereas actually changing a flight mode on the Vehicle may be rejected. Hence the two can get out of sync. Using the latest QGC Daily you should get a popup when the flight mode vehicle change is rejected.

**Comment by sn0west** [comment] 2016-04-11 21:43
I'm not sure if I understand it. In my example I do change FM frome FM 1 to FM 2 using my RC. But in all four cases it shows the FM from #3 in the top bar. 
How can I control the right flight mode then? It doesn't make any sense! 
I do test with FM wich do not require any GPS lock.

**Comment by DonLakeFlyer** [comment] 2016-04-11 22:53
Can you save your parameter set to a file and attach here then I'll try to see how you have things set up. Not quite sure if the right things are happening (but very confusing) or the wrong things are happening.

**Comment by sn0west** [comment] 2016-04-12 17:54
The Taranis is set as Lorenz showed in the howto videos.
I could only upload a zip!? Shall I upload my parameters somewhere else?
[160412_snowest_PIXRACER.params.zip](https://github.com/mavlink/qgroundcontrol/files/215620/160412_snowest_PIXRACER.params.zip)

**Comment by DonLakeFlyer** [comment] 2016-04-12 20:02
Zip is good, thanks.

**Comment by sn0west** [comment] 2016-04-13 05:33
Just to be sure, I 'm the only one who noticed this problem or does someone else also have it?

**Comment by DonLakeFlyer** [comment] 2016-04-13 16:12
Ok, I can repro this by:
* Loading your parameter set onto a pixhawk board and assigning channel 5 on my radio to a dail
* I also turned off kill and return switches since I didn't have those setup
* Go to flight mode config and spin the dialog to change flight mode. You'll see that what QGC thinks the flight mode should be according to PWM value doesn't match what the Vehicle thinks it should be.
* I've checked raw rc values and they seem correct with respect to what QGC thinks the flight mode should be

Keep in mind that for FM Config QGC is doing it own calculations to show flight mode hightlight. It doesn't not use mode from Vehicle.

Not quite sure what is going wrong on the Vehicle side. I think maybe there may be some confusion over simple flight mode setup veruse advanced.

**Comment by LorenzMeier** [comment] 2016-04-16 01:26
Do you guys run master or stable when you experience this?

**Comment by DonLakeFlyer** [comment] 2016-04-16 01:44
This was on master PX4, master QGC.

**Comment by sn0west** [comment] 2016-04-17 05:09
Yes master version

**Comment by LorenzMeier** [comment] 2016-04-17 21:30
@sn0west is this an actual problem or is just the indication in QGC wrong? @DonLakeFlyer This is not using fixed PWM ranges, but rather an equal span of six slots over the calibrated range.

**Comment by DonLakeFlyer** [comment] 2016-04-18 00:23
QGC ranges are wrong then. I'll fix it.

**Comment by LorenzMeier** [comment] 2016-04-18 16:54
I fixed this - it was incomplete in PX4 and in QGC, which made it very confusing.

**Closed by LorenzMeier** 2016-04-18 16:54 UTC

**Comment by sn0west** [comment] 2016-04-23 12:06
The Problem is still there, maybe only a gui issue? I could go out flying to chet if the flight mode is still the right one

![bildschirmfoto 2016-04-23 um 13 56 29](https://cloud.githubusercontent.com/assets/9918649/14761297/67819ac0-095c-11e6-9b6f-794beaa70bf6.png)
![bildschirmfoto 2016-04-23 um 13 56 45](https://cloud.githubusercontent.com/assets/9918649/14761296/67813fbc-095c-11e6-917f-5a5d840a7313.png)

**Comment by sn0west** [comment] 2016-04-27 05:51
I changed the value of fm2 on my taranis and it works now. But the pwm range of fm2 seams to be realy small. I don't see the value on qgc so I can't tell from what value to what value it is. I had to press seven time on my taranis to leav the fm2 witch seams to be a realy small range. 

But it works now so everything ok.
