### ISSUE TITLE
qmake6 not found in arm builds

### ISSUE THREAD

**Issue by chris-hagen** [mavlink/qgroundcontrol#10896] opened 2023-12-06 07:42 UTC
## Expected Behavior
Creating a new PR the pipeline does automatic code checks, that should run through as the code changes are valid.

## Current Behavior
After updating to Qt6 the checks fail for arm builds with the following error message:

```
/home/runner/work/_temp/Qt/6.6.1/android_armv7/bin/qmake: 7: /home/runner/work/_temp/Qt/6.6.1/gcc_64/bin/qmake6: not found
```

## Steps to Reproduce:
1. Push a new commit with minimal code changes
2. Create a PR from it

## Log Files and Screenshots
![Screenshot from 2023-12-06 08-42-12](https://github.com/mavlink/qgroundcontrol/assets/65018757/294976f8-bae6-41cf-a86a-1771a5b78ab6)

**Comment by DonLakeFlyer** [comment] 2023-12-07 10:23
New Qt6 Android build is known the be broken: https://github.com/mavlink/qgroundcontrol/issues/10887

**Comment by DonLakeFlyer** [comment] 2023-12-18 19:45
Duplicate of details in #10887

**Closed by DonLakeFlyer** 2023-12-18 19:45 UTC
