### ISSUE TITLE
Linux Daily Build (qgroundcontrol.tar.bz2) built by travis-ci doesn't work

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#2542] opened 2016-01-06 03:54 UTC

**Comment by dagar** [comment] 2016-01-06 04:22
It seems to be something to do with libQt5Core.so.5, which is the only lib that's different from my local machine.

**Comment by DonLakeFlyer** [comment] 2016-01-06 17:30
@pkocmoud Was saying it only showed up recently. Maybe a week old. Something recent broke it.

**Comment by pkocmoud** [comment] 2016-01-06 17:46
Initially I thought it was a bad daily build, since the stable release works fine. I plan on installing the most modern non-LTS version of Ubuntu as that may have a better video driver. However, the LTS is the better solution in my opinion.

**Comment by DonLakeFlyer** [comment] 2016-01-06 17:47
> may have a better video driver

The video driver thing is bogus, sorry about that. Both Daniel and I can reproduce this one our machine. Daily build is just broken.

**Comment by pkocmoud** [comment] 2016-01-06 17:48
So, should I delay the OS upgrade?

**Comment by DonLakeFlyer** [comment] 2016-01-06 18:52
It won't fix the problem.

**Comment by DonLakeFlyer** [comment] 2016-01-06 20:17
I was just building my own version of Qt on Ubuntu and got this while running configure:
```
Running configuration tests...
The test for linking against libxcb and support libraries failed!
 You might need to install dependency packages, or pass -qt-xcb.
 See src/plugins/platforms/xcb/README.
```

Seems vaguely similar to the above problem?

**Comment by DonLakeFlyer** [comment] 2016-01-09 23:41
@dagar Any news on this one? Want' to announce QGC APM Beta, but need this fixed for that.

**Comment by dagar** [comment] 2016-01-10 21:37
I still don't why it's broken when created on travis-ci, but works when created locally. I'll try another source of Qt for travis.

**Comment by dagar** [comment] 2016-01-11 04:51
I believe the linux package is missing qt plugins, but finding them locally. Working on a fix.

**Closed** 2016-01-13 21:46 UTC
Labels: All Firmware, Linux
