### ISSUE TITLE
Disable UVC video input by default

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#4112] opened 2016-10-06 20:33 UTC
QGC tries to open a video device (_NOT TO BE CONFUSED WITH DIGITAL VIDEO STREAMS_) by default and segfaults on a number of platforms (I believe we had issues on Android and iOS). I think we should disable this by default and let users enable it optionally.

Either QGC or Qt is very unstable on this feature and unless you have an analog-to-digital video USB stick connected it makes no sense for most people.

**Comment by LorenzMeier** [comment] 2016-10-06 20:35
@bkueng This is to track the crash that you were experiencing

**Comment by dogmaphobic** [comment] 2016-10-06 20:56
Qt crashes when "looking" to see if there is a camera. This is on Linux only. It works fine in all other platforms. This feature is disabled by default on Linux.

https://github.com/mavlink/qgroundcontrol/blob/master/qgroundcontrol.pro#L56-L61

**Comment by LorenzMeier** [comment] 2016-10-06 20:57
I'm telling you it crashes on that location on Android.

**Comment by LorenzMeier** [comment] 2016-10-06 20:58
Also, the whole logic seems backwards - why are you setting a define to disable something? Shouldn't it be enabled on each platform where we know its stable?

**Comment by dogmaphobic** [comment] 2016-10-06 21:00
> I'm telling you it crashes on that location on Android.

Android is Linux but there is no Android device with no Camera (that we use anyway).

> Also, the whole logic seems backwards - why are you setting a define to disable something? Shouldn't it be enabled on each platform where we know its stable?

It is stable and it has been fixed in newer versions of Qt. We're stuck with 5.5.1 so for the time being, I disabled it on Linux.

**Comment by DonLakeFlyer** [comment] 2016-10-06 23:49
Just FYI it doesn't crash on my Samsung tablet. In fact it shows the tablet camera in the little video box! Definitely need some user way to turn off.

**Comment by bkueng** [comment] 2016-10-07 05:51
Some more infos: QGC reproducibly crashes on startup, android with latest master. I don't even get to see the main widget.
http://pasted.co/1386a63d

**Comment by LorenzMeier** [comment] 2016-10-07 06:56
@bkueng Since we are using an x86 tablet the best initial step (given that x86 tablets are really weird on Android) would be to use this to exclude UVC there for now:
```
android {

    equals(ANDROID_TARGET_ARCH, armeabi-v7a) { 
        [doAndroidArmStuff]
    }
    equals(ANDROID_TARGET_ARCH, armeabi) {
        [doAndroidArmeabiStuff]
    }
    equals(ANDROID_TARGET_ARCH, x86)  {
        [doAndroidx86Stuff]
    }
}
```

**Comment by bkueng** [comment] 2016-10-10 10:07
Seems to work now, not sure what the problem was, but manually uninstalling QGC and flashing it resolved the problem.

**Comment by booo** [comment] 2022-11-01 19:50
Seems to be resolved.

**Closed by booo** 2022-11-01 19:50 UTC
