### ISSUE TITLE
QGC 3.3 Joystick: Joystick/ No RC Checks Manual Control lost.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#6264] opened 2018-03-25 22:05 UTC
PX4 1.7.3
QGC 3.3
Joystick: Mad Catz F.L.Y.5
Flying Wing. (VTOL)

When Joystick/ No RC Checks is used on arming it reports manual control lost and commands RTL which is rejected with a message Rejected RTL in a loop all the time until i press disarm.

![173 manual control lost on joystick no rc](https://user-images.githubusercontent.com/12617619/37880474-b629b74e-3091-11e8-9b97-43fc054d9ca5.png)

**Comment by DonLakeFlyer** [comment] 2018-03-30 17:28
I believe this is caused by the fact that when you initiall boot QGC joystick commands don't automatically start sending. You have to go to the Joystick page to get them to start, even if joystick is enabled.

**Comment by DonLakeFlyer** [comment] 2018-03-30 17:36
@jaxxzer @nanthony21 Joystick folks. Could someone help out and fix this?

If you turn on JoystickValuesLog can you see that they don't start pumping out until you go to the joystick page. I believe this is the case with 3.3 as well so the fix needs to start on that branch.

**Comment by nanthony21** [comment] 2018-03-30 22:59
@DonLakeFlyer I dug into it a bit today. It looks like this was introduced by my pull request #6117. I'll fix it this weekend. It looks like the "Stable v3.3" branch is unaffected.

**Comment by DonLakeFlyer** [comment] 2018-06-20 21:08
This should be fixed now

**Closed by DonLakeFlyer** 2018-06-20 21:08 UTC
