### ISSUE TITLE
4.1.0 cannot connect to server on TCP connect type

### ISSUE THREAD

**Issue by wetouns** [mavlink/qgroundcontrol#9367] opened 2021-01-22 15:59 UTC
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
logs in console
[E] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread

## Current Behavior
cannot connect to TCP server

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.create new connection
2.connection type select TCP
3.type your host address and port and then save
4.click connect button

## System Information
When posting bug reports, include the following information
- Operating System: Android 7.0
- QGC Version: 4.1.0
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: F405-wing
- Autopilot (with version): 4.0.5 stable

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by DonLakeFlyer** [comment] 2021-01-22 18:07
Duplicate of #9331

**Closed by DonLakeFlyer** 2021-01-22 18:07 UTC
