### ISSUE TITLE
Deleting inserted waypoints bug

### ISSUE THREAD

**Issue by kellysteich** [mavlink/qgroundcontrol#3987] opened 2016-08-29 13:58 UTC
When planning a mission, inserting a waypoint by selecting another waypoint and choosing "Insert" from its menu and then deleting the inserted waypoint breaks the mission planner view, as seen in the following screenshots:

| mission in beginning | mission after inserting a waypoint | mission after deleting said waypoint |
| :-: | :-: | :-: |
| ![screenshot from 2016-08-29 15-47-47](https://cloud.githubusercontent.com/assets/5629242/18053548/532a14d6-6e00-11e6-908d-01a6a08142a2.png) | ![screenshot from 2016-08-29 15-48-06](https://cloud.githubusercontent.com/assets/5629242/18053554/58717fce-6e00-11e6-9562-fa6271185735.png) | ![screenshot from 2016-08-29 15-48-20](https://cloud.githubusercontent.com/assets/5629242/18053561/5d9a3d24-6e00-11e6-9c4b-a0a80a85db80.png) |

To reproduce:
- create a few waypoints normally, by clicking inside the map
- then insert a waypoint, by selecting one of the previously created waypoints and choosing "Insert" from its menu
- delete this inserted waypoint, by choosing "Delete" from its menu

Saving a mission with a waypoint that has been inserted and reloading it solves the problem and the waypoint can then be deleted normally.

**Comment by birchera** [comment] 2016-08-31 12:54
We did some research on this but could not quite put our finger on the right spot. We made the following observations:

* It only occurs when adding items in the middle of the list and not appending them. The function [insert(i, object)](https://github.com/mavlink/qgroundcontrol/blob/d937bd2b6ac4048a5872cd5562fdd614ab3fb8f1/src/QmlControls/QmlObjectListModel.cc#L171) seems to call [different methods](http://doc.qt.io/qt-4.8/qlist.html#insert) Qt internally depending on the value of i.
* We could not reproduce it when setting a breakpoint in the function [QmlObjectsListModel::removeAt](https://github.com/mavlink/qgroundcontrol/blob/d937bd2b6ac4048a5872cd5562fdd614ab3fb8f1/src/QmlControls/QmlObjectListModel.cc#L138).

**Comment by DonLakeFlyer** [comment] 2016-08-31 17:18
It is most likely a Qt draw bug. I've hit this before with insert/delete. The trick is to find a workaround that works. Need to try it on a mobile build to see if it a QQuickWidget problem versus native Qml. Haven't had time yet.

**Comment by DonLakeFlyer** [comment] 2016-09-04 18:51
This repros on mobile native qml QGC as well

**Comment by DonLakeFlyer** [comment] 2016-10-20 18:44
Testing for fix in Qt 6.2

**Comment by DonLakeFlyer** [comment] 2016-12-28 17:49
Fixed in 5.8

**Comment by DonLakeFlyer** [comment] 2016-12-28 17:51
Will be fixed in 3.2 when we move to Qt 5.8

**Comment by DonLakeFlyer** [comment] 2017-03-19 18:14
Fixed now that we are on Qt 5.7

**Closed by DonLakeFlyer** 2017-03-19 18:14 UTC
Labels: Bug
