### ISSUE TITLE
UI Issues in QGC v4.1 and recent. 

### ISSUE THREAD

**Issue by sunny52266** [mavlink/qgroundcontrol#9433] opened 2021-02-12 19:24 UTC
1. Certain UI features not visible until the application is scaled to around 70 percent on android phone. My current phone is oneplus 6. 

2. The translucent nature of the main dock causes readability issues in sunlight specially when the satellite imagery is turned on and bare ground is in the background. For example: ![Screenshot_20210213-001142.jpg](https://user-images.githubusercontent.com/68956206/107812627-c7850080-6d91-11eb-905c-7208cca83169.jpg)

**Comment by Davidsastresas** [comment] 2021-02-13 15:07
fixed in  #9436

**Comment by DonLakeFlyer** [comment] 2021-02-16 20:03
I think this screenshot is showing more bugs than just the visibility problem. You can see how the coloring of the text versus the labels differs. I need to take a look at that to see if there is an additional problem.

**Comment by DonLakeFlyer** [comment] 2021-02-17 01:02
Indoor theme looks like crap as well over certain maps. I think in both cases the values panel needs to be opaque.

**Comment by Davidsastresas** [comment] 2021-02-17 23:08
That makes sense. What do you think is the cause of the other bug? it seems like the bold feature of the digits is not what it should right?

**Comment by DonLakeFlyer** [comment] 2021-03-02 19:05
> 1. Certain UI features not visible until the application is scaled to around 70 percent on android phone. My current phone is oneplus 6.

@sunny52266 What else is missing?

**Comment by sunny52266** [comment] 2021-03-02 19:35
1. Some times the back button does not exit the application. 

2. When use vertical instrument panel is checked, the instrument panel disappears. 

3. There is no option for trigger camera now as there was in previous versions. 

4. Second GPS info does not appear in the gps parameters selection in the parameters dock type thingy on the main display that needed to be opaque. 

These are the ones from the top of my head.

**Comment by DonLakeFlyer** [comment] 2021-03-02 20:22
> 2\. When use vertical instrument panel is checked, the instrument panel disappears.

Fixed. Will show up when a new stable is marked.

> 3\. There is no option for trigger camera now as there was in previous versions.

This should be fixed as well. Will show up when new stable is marked.

> 4\. Second GPS info does not appear in the gps parameters selection in the parameters dock type thingy on the main display that needed to be opaque.

This was not supported in previous versions. Support was just added and is supported in Daily builds.

**Comment by sunny52266** [comment] 2021-03-03 08:30
@DonLakeFlyer Must be good then. Shall I close this issue now?

**Closed** 2021-03-03 16:03 UTC
