### ISSUE TITLE
Log Download:  100% use of one CPU core

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#9882] opened 2021-09-21 09:07 UTC
## Expected Behavior
low CPU usage for transferring kilobytes

## Current Behavior
100% of one CPU core is used, even on very powerfu CPU's and 57600kbps download.

## Steps to Reproduce:
1. do log download over MAVLink , 
2. observe CPU usage

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 21.04
- QGC Version: current master
- QGC build: daily
- Flight Controller: CubeBlack
- Autopilot (with version): AC4.0.3

## Detailed Description
n/a

## Log Files and Screenshots
n/a

**Comment by HTRamsey** [comment] 2024-06-03 02:47
Duplicate of  #4656

**Closed by HTRamsey** 2024-06-03 02:47 UTC
Labels: Report: Bug
