### ISSUE TITLE
Fixed Wing Landing Pattern

### ISSUE THREAD

**Issue by cody303** [mavlink/qgroundcontrol#6137] opened 2018-02-13 20:29 UTC
Using the Pixhawk and Ardupilot code base the landing pattern has an orbit to altitude then a landing point. Sometimes the autopilot recognizes the waypoint as complete on the inside of the orbit radius causing the plane to turn prematurely in closer to the landing point , making a steeper decent. (see attached picture). 

![landing angle](https://user-images.githubusercontent.com/32106808/36171970-be203f4e-10c1-11e8-99c8-0de799b8cbc9.PNG)
I think this could be fixed with another waypoint in between the landing and the obit radius that it would need to hit before descending. That way the orbit could be placed further back, and the distance where the decent started would be at the same altitude and distance every time.

**Comment by DonLakeFlyer** [comment] 2018-02-13 21:12
@antiheavy Have you noticed this as well?

I wonder if the real fix for this is some sort of new firmware command? To force it to do at least a partial cycle around the loiter. Not sure if adding more complexity/waypoints is the way to go here.

**Comment by Antiheavy** [comment] 2018-02-14 04:34
I have not seen this issue.  Done many hundreds of landings using the QGC Landing pattern in PX4 fixed wing firmware and it pretty much always works as intended.  It always breaks out of the loiter when both the altitude is reached and the vehicle is lined up on the final approach.  Entering/holding the loiter can get a little wonky in windy conditions sometimes, but that isn't the mission plan's fault.  Ultimately it always gets lined up before exiting the loiter, even if it has to complete another time around the loiter first.

@cody303 mentioned APM, does APM fully implement the MAV_CMD_NAV_LOITER_TO_ALT to include the "Heading Required = True" field?  This is what forces the exit criteria to also be lined up with the landing waypoint.  I couldn't find where in the APM code this is implemented, but I easily could have missed it.  Maybe someone who knows more about APM could verify if implementing this would be the real fix.

**Comment by DonLakeFlyer** [comment] 2018-02-14 18:22
@cody303 You were seeing this on PX4 as well? My thinking was similar to Todd's, that something possibly wrong with ArduPilot MAV_CMD_NAV_LOITER_TO_ALT implementation.

**Comment by cody303** [comment] 2018-02-14 18:49
Yea I don't think it supports the heading requirements.  We are not currently using PX4, but maybe it is time to switch. 

Cody

**Comment by DonLakeFlyer** [comment] 2018-02-14 18:53
It needs to support MAV_CMD_NAV_LOITER_TO_ALT.param4 = 1 which indicates a tangent cross-track exit. I had thought it supported that. But I have a feeling they may have implemented in a different way which doesn't quite end up working to same all the time. Whereas PX4 always circles the loiter and exits.

**Comment by DonLakeFlyer** [comment] 2018-02-16 18:40
So not much I can do here.

**Comment by DonLakeFlyer** [comment] 2018-02-18 18:01
@cody303 I'm going to close this. Looks like ArduPilot needs to do two possible things:
* Support tangent cross-track exit
* or if they do it appears to have bugs where in some cases the tangent exit is not in the direction of the next waypoint

**Closed by DonLakeFlyer** 2018-02-18 18:01 UTC

**Comment by kikislater** [comment] 2018-04-05 14:35
So this one will never work with Arduplane ?

**Comment by DonLakeFlyer** [comment] 2018-04-05 15:55
You'll have to ask the ArduPlane folks about that. I would suggest providing them with an example where it doesn't quite do the right thing and flight logs in an Issue.

**Comment by magicrub** [comment] 2018-04-06 18:27
@cody303 @DonLakeFlyer  This all definitely works in ArduPlane but there is a corner case that just got fixed here https://github.com/ArduPilot/ardupilot/issues/7934 where if you're using a LOITER_TO_ALT but performing a turn and you're already at the altitude in the first couple seconds of the loiter then the circle is not much of a circle. This was not planned to be in the current 3.8.5beta but I think it would be a good candidate to include.

**Comment by DonLakeFlyer** [comment] 2018-04-06 18:40
Ah, fantastic.
