### ISSUE TITLE
pixhawk latest firmware connection issue

### ISSUE THREAD

**Issue by blankered** [mavlink/qgroundcontrol#2563] opened 2016-01-09 15:27 UTC
Hello,
I was using qgroundcontrol v2.8.0 to update my pixhawk to the latest firmware and found that it does not connect to qgroundcontrol after flashing it. It does however connect to qgroundcontrol after flashing the APM firmware. I am confused why this is happening, the ports in qgroundcontrol were the same when compared to the dmesg output in Ubuntu 14.04. Is this a firmware issue or qgroundcontrol issue?

**Comment by LorenzMeier** [comment] 2016-01-09 15:48
Can you please re-flash? I have cross tested this and it should work just fine with the latest code.

**Comment by LorenzMeier** [comment] 2016-01-09 19:44
It would be fantastic if you could re-try and provide us an update.

**Comment by blankered** [comment] 2016-01-10 20:12
I reflashed the pixhawk to the px4 firmware using v2.8.0. After I flashed it, I disconnected and reconnected the USB. I checked the dmesg output and verified the connection settings in QGroundControl. QGroundControl can find the px4 and flash it accordingly but wont bring up the parameters or calibration page. I have tried both the pre-compiled version and the qt compiled version with the same effect.

**Comment by DonLakeFlyer** [comment] 2016-01-10 21:20
> Error on link /dev/ttyACM0. Error connecting: Could not create port. Permission error while locking the device

This is an OS problem not a GGC problem.

**Comment by blankered** [comment] 2016-01-10 21:25
@DonLakeFlyer This only occurs when I flash the px4 firmware. GGC connects when I flash the apm firmware. Why would it be firmware specific?

**Comment by LorenzMeier** [comment] 2016-01-10 21:28
@blankered Its still an OS issue. It likely has nothing to do with Firmware but the sequence of your trial and error steps. Have you tried re-flashing the most recent PX4 Firmware (like from *now*) and trying again?

Also make sure to connect to the back of your PC (NOT A HUB) and to not power your whole drone off USB (your USB doesn't provide enough power)

**Comment by DonLakeFlyer** [comment] 2016-01-10 21:29
I can't answer that, but that error is exactly what you get when there is an OS permission issue. Given the fact that you are clicking a Connect button I assume you are running a Stable build. I'd also make sure you are using a daily build.

**Comment by blankered** [comment] 2016-01-10 22:24
I have both the stable build and daily build. I tried flashing the px4 firmware using the daily build, a usb port off the back of my tower, and battery pack connected. It still fails to connect after flashing the firmware, the pixhawk boots and starts to flash red rapidly. If I use QGC to flash the apm firmware then I have no problems getting the pixhawk to connect and show the summary page.

**Comment by LorenzMeier** [comment] 2016-01-10 22:35
Can you flash it again today, unless you have done that already? I want to be sure that both QGC and the Firmware are absolutely recent - depending on the combination they need to be absolutely recent.

**Comment by blankered** [comment] 2016-01-10 22:52
OK, so I reformatted the SD and it fixed itself. QGC has established a connection with the px4 after the flashing process. I reflashed using the daily build with the px4 master build firmware. I am going to do so testing to see if the problem is actually fixed and report back later. Thank you for your help.

**Comment by LorenzMeier** [comment] 2016-01-10 22:57
That's quite interesting. Could you try that at the end again to see if maybe flashing APM actually threw off the PX4 boot?

**Comment by DonLakeFlyer** [comment] 2016-01-11 20:43
@blankered What's the state of this? Is there a QGC problem here?

**Comment by Flugsicherung** [comment] 2016-01-15 12:00
Hello together. I have exact the same Problem as "blankered" I can´t connect to my Pixhawk after flashing the stable Firmware on QGC 2.8.0.  I am useing QGC on Windows 7 64 Bit. Flashing works only if the Pixhawk is NOT powered with external Power. Only if I flash with USB Power onIy can I flash it otherwise the flashing is not start up. On QGC 2.7.1 it works fine so I guess it must be a issue in QGC 2.8.0 or in last stable Firmware.

**Comment by LorenzMeier** [comment] 2016-01-15 12:03
It is designed to prevent reboots if the system is pre-armed, which probably happens when you connect the battery. So it all works as it should.

@DonLakeFlyer Do the instructions ask users to *ONLY* have USB connected already?

**Comment by Flugsicherung** [comment] 2016-01-15 12:13
I flash Firmware 1.1.0 and I can connect to the Pixhawk and the Summary Page is shown.
I make a Test and flash 1.1.1 again.....

**Comment by Flugsicherung** [comment] 2016-01-15 12:17
I flash Firmware 1.1.1 and same Problem, I can´t connect to Pixhawk.....

**Comment by DonLakeFlyer** [comment] 2016-01-15 18:16
> Do the instructions ask users to ONLY have USB connected already?

It doesn't say no battery. That wording is starting to read like a book! I'll change it. I think I'm going to change it to output after a failed flash as well.

**Comment by Flugsicherung** [comment] 2016-01-15 19:02
Sorry but why do you close this issue? The Problem is not to make the flash of the Firmware. Flashing without battery works fine. But if I flash Firmware 1.1.1 I can´t get a connection after successful flashing, but with Firmware 1.1.0 it works!!!!
Please can you explan it for me, thanks.

**Comment by DonLakeFlyer** [comment] 2016-01-15 19:22
Can you switch to using a QGC Daily Build. Stable is quite old and this point. If you still can't connect after that. See here for getting connection logging: http://www.qgroundcontrol.org/logging. Then put log output here.

**Comment by LorenzMeier** [comment] 2016-01-15 19:49
@Flugsicherung I'm checking the release. Let me make sure I didn't screw up and something bad slipped in.

**Comment by Flugsicherung** [comment] 2016-01-16 08:10
@DonLakeFlyer with Software do you mean? The Beta Version? If so my Virus Scanner (AVG) delete this File, he found a Virus inside. So I put the File to https://www.metascan-online.com the Scanner found a Virus too. 
![beta installer](https://cloud.githubusercontent.com/assets/16131122/12371344/9b894044-bc30-11e5-8fd1-02be8eded25b.PNG)

@LorenzMeier Thanks, I thing the last "Stable" Versions of QGC (2.8.0) and PX4 Firmware (1.1.1) should play together. Normal Users takes only this Versions.

**Comment by Flugsicherung** [comment] 2016-01-16 09:14
Today I flash the Master Version of the PX4 Firmware but same happens, I can´t connect to the Pixhawk with QGC 2.8.0 flashing works fine. Then I flash the Version 1.1.0 back to the Pixhawk and I can connect without Problems.

**Comment by DonLakeFlyer** [comment] 2016-01-16 17:18
It is extremely doubtful that qgroundcontrol has a virus in it. This is a false positive. You should report the false positive to you virus folks.

**Comment by DonLakeFlyer** [comment] 2016-01-16 17:19
![screen shot 2016-01-16 at 9 19 21 am](https://cloud.githubusercontent.com/assets/5876851/12373569/43c50846-bc32-11e5-96f1-de711b01a9a5.png)

**Comment by DonLakeFlyer** [comment] 2016-01-16 17:24
I'll deal with reporting the false positive.

**Comment by DonLakeFlyer** [comment] 2016-01-21 20:04
Is this still a problem?

**Comment by LorenzMeier** [comment] 2016-01-21 23:03
Should be fixed by a Firmware fix and the SD card warning fix.

**Closed by LorenzMeier** 2016-01-21 23:03 UTC
Labels: PX4 Firmware

**Comment by Flugsicherung** [comment] 2016-01-22 09:45
Ok I wait for the next Firmware, thanks.

**Comment by LorenzMeier** [comment] 2016-01-22 09:46
You don't have to wait. Just flash master (see the checkbox on the bottom of the flash dialog for "advanced options").

**Comment by salim616** [comment] 2016-12-12 17:24
Hi  @LorenzMeier 
I got the same problem as above. can not connect to my Pixhawk. i am V3.0.1
![image](https://cloud.githubusercontent.com/assets/6405695/21109126/92aede16-c08f-11e6-8fa2-b7891cf3621e.png)
any help ?

**Comment by msadowski** [comment] 2017-04-10 07:29
I just run into the same problems as described in this thread (there was APM previously installed on my board). The Px4 would flash through QGroundControl and using make in the repository but it would not boot properly (QGroundControl didn't show anything). I tried latest release, latest commit from master branch and even some old commit from February. 

As @blankered noticed formatting the SD card helped and now Pixhawk boots properly.

**Comment by DonLakeFlyer** [comment] 2017-04-10 15:33
This problem doesn't have anything to do with QGC. If there is a problem it is  firmware problem.

**Comment by feemi** [comment] 2019-07-04 13:00
Hi @LorenzMeier @DonLakeFlyer,

This issue was closed long time ago. Could you find the root cause of the problem ?

We are having exact issue with various versions including v1.9. We are having this problem in mac and windows but not in ubuntu with pixhawk 2.1 cube fmu-v3 board.

pixhack5+ fmu-v5 is working properly.

Steps to reproduce:

1. If i reflash px4 firmware nothing changes. 
2. If i flash to ardupilot it connects successfully to qgc.
3. Then i reflash px4 it also connects successfully to qgc.
4. But if i select airframe or change any parameter and restart then the issue raises again.

Note: This problem only occurs with usb connection. It connects successfully from telem1 uart via ftdi or similar.

**Comment by DonLakeFlyer** [comment] 2019-07-04 17:07
Can you enter a new issue with exact details. There are multiple things dicussed in this issue. So what the "exact issue" is unclear.
