### ISSUE TITLE
[BUG] Android only - No Ground Level Data received

### ISSUE THREAD

**Issue by b14ckyy** [mavlink/qgroundcontrol#6928] opened 2018-10-18 14:41 UTC
I have an issue with QGC on Android. With Version 3.4.4 (also tested with 3.4.3) no Ground Level Data are received when planning a Mission with AGL Waypoints. 

On Windows and Ubuntu Version all is fine. Tested with Google Map and Bing Map > Same issue

Reproduce:

- Fresh install of QGC 3.4.3 or 3.4.4 on android 8.0
- LTE or WiFi doesn't matter
- plan mission with AGL waypoints

Result:
- Level Bars on lower left will stay yellow
- no save or upload of mission possible due to missing ground level data

Tried Daily Build from google play yesterday but it crashes on start.
Tested on an Galaxy S8 and My Xperia XZ with same result. 
Also manual map download with activated elevation data fetching does not work. Map is downloaded but no elevation data will be loaded.

**Comment by DonLakeFlyer** [comment] 2018-10-24 18:09
I believe this is a problem which shows up on Android 8+

**Comment by DonLakeFlyer** [comment] 2018-10-24 19:06
We know what the problem is. It has to do with Qt and crypto libs. The real question is how to work around it though. Can you enter I separate issue on daily build crash?

**Comment by b14ckyy** [comment] 2018-10-24 19:07
yes I'll do. I've already sent you crash report via android a few days ago. I'll do it again and post the log here if provided.

**Comment by DonLakeFlyer** [comment] 2019-01-19 18:57
This is fixed now

**Closed by DonLakeFlyer** 2019-01-19 18:57 UTC
