### ISSUE TITLE
ADS-B data feed not reliably displayed.

### ISSUE THREAD

**Issue by timtuxworth** [mavlink/qgroundcontrol#10143] opened 2022-02-02 18:31 UTC
[ADSB-2022-02-02.txt](https://github.com/mavlink/qgroundcontrol/files/7989320/ADSB-2022-02-02.txt)
## Expected Behavior
Planes are displayed on the map when they are sent by ADS-B

## Current Behavior
Planes don't reliably show up. Sometimes they do, then disappear, sometimes they don't even show. I have a web app showing nearby planes, netcat showing my dumb1080 feed from my raspberry pi and Mission Planner reading the same feed shows planes that don't show up on th QGC map. Also the QGC logs viewer shows that QGC is receiving the ADSB feed (see attached screenshot), but the planes shown in the log are not showing on the map.

This is on a Mac if it matters (MacPro 2021 version M1Pro running 12.1

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Configure QGC to use my local (raspberry pi) ADS-B server at port 30003
2. Go "back" to the main map. 
3. Planes don't display most of the time.
4. Go to Application Settings ->Console turn on "Trace" trace log shows the ADSB data is being received. I've clicked the "Save App Log" button and uploaded a copy of the file that was saved.

## System Information
When posting bug reports, include the following information
- OSX 12.1
- 4.2.0
- Stable

## Detailed Description
![Screen Shot 2022-02-02 at 10 17 57 AM](https://user-images.githubusercontent.com/5266784/152215710-e675daca-5db7-4ca0-8f52-93cafe4308d2.png)
![Screen Shot 2022-02-02 at 10 16 25 AM](https://user-images.githubusercontent.com/5266784/152215723-c5e2928a-3244-40a7-8b2f-ce5f6467e5d2.png)

## Log Files and Screenshots
-Screen shots attached
-App log attached.

**Comment by zdanek** [comment] 2022-02-03 15:34
@timtuxworth I can confirm this. I don't know if this is a bug - it worked better before or a lack of functionality. Seems that QGC parses only a few of available ADSB messages. I've checked it with my Flightradar24 receiver that feeds messages to port 30003. I've checked that output shows more data (more relevant data and more planes nearby) than are displayed in QGC.

I can fix it if I have a green light from @DonLakeFlyer  that it will be merged (if code quality meets requirements) so my effort will make sense :)

**Comment by timtuxworth** [comment] 2022-02-03 15:37
I'd be happy to test it! Thanks @zdanek

**Comment by mrpollo** [comment] 2022-02-08 16:48
hey @zdanek if you are willing to contribute we can make our best effort to help you get this merged, please submit a PR, please add me as a reviewer

**Comment by timtuxworth** [comment] 2022-02-08 17:04
This is a raw netcat of the dump1090 output I'm getting from my RadarBox.
[dump1090test.txt](https://github.com/mavlink/qgroundcontrol/files/8025949/dump1090test.txt)

**Comment by DonLakeFlyer** [comment] 2022-02-08 17:44
> Seems that QGC parses only a few of available ADSB messages.

I don't think that's the problem. QGC parses the same messages that Mission Planner does (3/4/1). 

I would guess it's either a problem with vehicle expiry or some sort of drawing problem. You can see from @timtuxworth log that there were two vehicles to it's seeing and they both expire. @zdanek If you can debug it through that would be helpful. First step is to debug whether the ADSBVehicle object are correctly being created/expired from the message traffic. If that seems to be working correctly then it's a ui display problem. If a UI problem something wrong in FlyViewMap.qml which does the display.

**Comment by DonLakeFlyer** [comment] 2022-02-08 17:46
@zdanek Also if you are in this code some additional logging for when adsb vehicles are added/removed from the list would be helpful for debugging.

**Comment by zdanek** [comment] 2022-02-08 19:28
@mrpollo thanks for your support. I know that code because I've been making some experiments lately with ADSB feeds and that's why I volunteer to fix this.

@timtuxworth thanks for the dump.

@DonLakeFlyer I saw some problems earlier. I also suspect some issues with timeouts. I'll add more logging.

**Comment by DonLakeFlyer** [comment] 2022-02-08 19:33
> I know that code because I've been making some experiments lately with ADSB feeds and that's why I volunteer to fix this.

@zdanek Thank so much for helping out.

**Comment by Autonomost** [comment] 2022-02-16 01:40
Hi All, Please let me know if I should create a separate post for this. 

The altitude and callsign for planes on ADSB do not show up on the iOS version of QGC. I've tried all the UI scaling parameters and no luck. Does anyone in this thread know any of the iOS devs? This is my first time posting in the QGC github and would appreciate any help/pointers. 

![IMG_7394](https://user-images.githubusercontent.com/9661687/154179781-6351a93a-b8c1-4256-be28-f5e23d3b5c57.PNG)

**Comment by zdanek** [comment] 2022-02-16 09:25
@Autonomost did you try build from my fix? 
See list of builds on the left and built files at the bottom
https://github.com/mavlink/qgroundcontrol/pull/10170/checks

**Comment by DonLakeFlyer** [comment] 2022-02-16 16:51
The iOS version of QGC is way out of date. At this point you have to build it yourself to get the latest version.

**Comment by Autonomost** [comment] 2022-02-18 21:36
@zdanek Nope I did not, haven't built iOS apps from scratch yet. 

@DonLakeFlyer thats a bummer. Is there anyone I can ping about that? Or should i compile latest and submit a PR for whoever manages the app store release?

**Comment by DonLakeFlyer** [comment] 2022-02-19 03:59
> Is there anyone I can ping about that? Or should i compile latest and submit a PR for whoever manages the app store release?

Not really. The person who managed and manually dropped iOS releases has been gone for multiple years now.

**Closed** 2022-02-21 17:25 UTC
Labels: Bug
