### ISSUE TITLE
Request to Add Support for Antenna Tracker

### ISSUE THREAD

**Issue by Pskoog3** [mavlink/qgroundcontrol#10216] opened 2022-03-20 18:54 UTC
It would be very helpful to add antenna tracker support for QGC like the one available for Ardupilot.
I am pretty sure many users are interested and similar request has been submitted before.

**Comment by booo** [comment] 2022-11-02 16:15
Duplicate of https://github.com/mavlink/qgroundcontrol/issues/10258. Please don't post feature request twice.

**Closed by booo** 2022-11-02 16:15 UTC
