### ISSUE TITLE
firmware upgrade hangs on ubuntu 16.04

### ISSUE THREAD

**Issue by barchstien** [mavlink/qgroundcontrol#5816] opened 2017-11-01 14:16 UTC
Hi Everyone

 - Working on Ubuntu 16.04
 - Using QGroundControl v3.2.5, freshly downloaded
   Tried both AppImage and Archive
 - Board is Pixhawk 2 (the "cube" stuff)
 - tried both ardupilot and px4 stable release, thought I don't think it matters at this stage

I start QGC, click on firmware, then it expects me to plug the flight controller to the usb port
Plugging, selecting the firmware, pressing ok, everything goes fine, until : 
"Programming new version..." hangs forever
Looking at the blue progress bar, it stops at random progress

I've done the same test on a windows machine, and it works fine (what a shame :-p )
I've, of course, removed modemmanager and added my user to the group : 
cat /etc/group | grep dialout
dialout:x:20:bastien

![screenshot from 2017-11-01 14-55-28](https://user-images.githubusercontent.com/10419986/32278768-003bdf5c-bf17-11e7-911a-7e0def211816.png)

I can post more info if needed
Also fluent in c/c++/linux but never went into QGC code and would be glade to get hands on if someone points me to a specific place

Thanks in advance

**Comment by barchstien** [comment] 2017-11-01 23:30
Also, once the pixhawk 2 has been flashed (firmware installed) from windows, QGC on ubuntu 16.04 work perfectly fine... except for firmware install of course

**Comment by DonLakeFlyer** [comment] 2017-11-02 18:00
@dagar Do you have a Cube to test with?

**Comment by barchstien** [comment] 2017-11-02 18:09
yep, having it right before my eyes

**Comment by DonLakeFlyer** [comment] 2017-11-02 18:11
@barchstien Is it only the Cube your are having problem with. Or can you not flash any type of board?

**Comment by barchstien** [comment] 2017-11-02 18:13
@DonLakeFlyer only having this cube in my lab, other boards are in the main lab, that I gonna be visiting by the end of the month.
Do you know if I can get the output of the console when trying to upload the firmware ? That may give out some clues ?

**Comment by DonLakeFlyer** [comment] 2017-11-02 20:29
Turn on FirmwareUpgradeLog: https://docs.qgroundcontrol.com/en/SettingsView/console_logging.html. Save the output and paste or zip here.

**Comment by barchstien** [comment] 2017-11-02 23:39
Here it goes
[5816_log.txt](https://github.com/mavlink/qgroundcontrol/files/1439687/5816_log.txt)
 - At he beginning : FirmwareUpgradeLog.debug=true\nFirmwareUpgradeVerboseLog.debug=true
 - Then I went into firmware upgrade, til it starts doing all the : _findBoardOnce
 - Then it finds the board, and downloads the available firmwares
 - Erase is fine
But nothing more, and QGC is frozen

**Comment by barchstien** [comment] 2017-11-06 13:25
ping ?

**Comment by dagar** [comment] 2017-11-06 16:26
I've been seeing this as well (QGC ~master built from source) on various pixhawks. It needs to be investigated and resolved before the next PX4 stable release.

**Comment by dagar** [comment] 2017-11-06 16:30
[qgc_px4fmu-v4pro_fail.txt](https://github.com/mavlink/qgroundcontrol/files/1446977/qgc_px4fmu-v4pro_fail.txt)

So far I can only confirm what @barchstien reported, but I don't see anything in the log.

**Comment by dagar** [comment] 2017-11-06 16:32
![image](https://user-images.githubusercontent.com/84712/32451958-33d4650a-c2e6-11e7-9425-0c4815f44a94.png)

**Comment by larsks** [comment] 2017-11-07 13:19
Is this a dupe of #5519?

**Comment by barchstien** [comment] 2017-11-07 15:56
Ok, got some good news
I've forked/clone QGC repo
Compiled in debug and run/debug it, with some extra trace
And flashing the board started to work !
Typical race condition stuff, to my mind (works in debug or with extra trace, not in release)
So I added a 1msec sleep before the call to tcdrain(), and flashing works perfectly fine many times in a row. If I remove the 1msec sleep, flash hangs just like expected. Also using 10msec sleep helps, but flashing gets pretty slow. Using less than 1msec isn't enough to get flash to work
@dagar @DonLakeFlyer I guess this sleep is more a workaround than a fix. I could do a pull request if you want ?

Also, I've added : 
    `if (::tcdrain(fd) < 0) {
        qCDebug(FirmwareUpgradeLog) << "::tcdrain(fd) failed : " << ::explain_tcdrain(fd);
    }`
But tcdrain() just hangs, so I didn't get any more useful data

Could it be that the hanging is due to a bug in the UART driver ?
I'm curious about it, gonna try check it out, see if I get anything

**Comment by barchstien** [comment] 2017-11-07 22:50
Tried to find out which driver was used, using 
`dmesg | grep driver`
Gave back 
`[  130.123116] usbcore: registered new interface driver cdc_acm`
`[  130.123117] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters`
So it's cdc_acm driver
Looking [here](https://www.kernel.org/doc/Documentation/usb/acm.txt)
Sounds to me like a very mainstream, long existing driver, so I guess nothing wrong in there
Conclusion, I'm back to searching a way to fix that better than just using just before ::tcdrain()
`QThread::usleep(1000);`

**Comment by DonLakeFlyer** [comment] 2017-11-07 23:22
> Is this a dupe of #5519?

Most likely.

**Comment by DonLakeFlyer** [comment] 2017-11-07 23:24
Can you flash the board with APM Planner 2?

**Comment by barchstien** [comment] 2017-11-07 23:33
APM or PX4 doesn't make a difference
Flash hangs, except when adding msleep(1) before tcdrain()

**Comment by DonLakeFlyer** [comment] 2017-11-07 23:37
I'm talking about APM Planner2 the application.

**Comment by barchstien** [comment] 2017-11-07 23:39
ok, installing it

**Comment by barchstien** [comment] 2017-11-07 23:46
yes, flashing the firmware with APM Planner2 works fine

**Comment by barchstien** [comment] 2017-11-08 12:36
Been checking APM Planner2 code. It doesn't used termios (tcdrain), but rely on [QSerialPort](http://doc.qt.io/qt-5/qserialport.html)
Is it an option to move from termios to QSerialPort ?The former is cross platform, while termios is linux/unix only

**Comment by DonLakeFlyer** [comment] 2017-11-09 21:26
I can't seem to get 3.2.5 to hang, but master does. I didn't think it was possible to switch to QSerialPort since it didn't support direct writing. But if APM Planner to is using that then I guess it works.

**Comment by DonLakeFlyer** [comment] 2017-11-10 19:06
Linux folks can you build the pull and see if it works for you. I run Ubuntu in a VM and it can sometimes show different results than native. I think it's working now though.

**Comment by barchstien** [comment] 2017-11-12 19:09
@DonLakeFlyer Just cloned DonLakeFlyer:FirmwareUpgradeQSerialPort from https://github.com/mavlink/qgroundcontrol/pull/5835
Compiled it in Debug and Release and tried a couple of times to load the firmware... And it works like a charm !
Thanks
Still on Ubuntu 16.04 with Pixhawk 2

**Comment by DonLakeFlyer** [comment] 2017-11-12 19:40
Phew, good news. Thanks for testing.

**Comment by aftersomemath** [comment] 2017-11-12 23:35
I had the same issue on Ubuntu 16.04 and #5835 fixed the issue as well.

**Comment by DonLakeFlyer** [comment] 2017-11-12 23:45
Verified that is works on OSX, Ubuntu and Windows.

**Closed by DonLakeFlyer** 2017-11-12 23:45 UTC
Labels: Bug, Linux

**Comment by vijay609** [comment] 2018-01-12 01:37
I am hitting this in the latest version of the QGC 3.2.7 on Ubuntu 16.04. I am trying to install px4fmuv2_lpe version 1.6.3 (after downloading it locally and pointing QGC to it)

**Comment by eirikaso** [comment] 2018-01-26 11:05
I have this exact problem as well. 
Just downloaded the appimage again. Are these changes incorporated into the appimage file?

**Comment by vijay609** [comment] 2018-01-26 18:29
Here's what worked for me in QGC 3.2.7 on Ubuntu 16.04
1. Click the "Q" sign on the top left corner of the window.
2. Go to "General". In the "AutoConnect to the following devices:", uncheck every thing except for "Pixhawk".

**Comment by DonLakeFlyer** [comment] 2018-01-29 22:37
You need to use a daily build to get the fixes.

**Comment by eirikaso** [comment] 2018-01-30 07:45
Thanks!
Didn't work to uncheck all the boxes, but using the daily build did :)

**Comment by dronecrewkari** [comment] 2018-02-02 04:44
Actually, I have the same problem
