### ISSUE TITLE
Current Daily: terrain altitude bar seems wrong

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#9236] opened 2020-12-05 16:05 UTC
Current daily build seems to have something going on with the terrain display.  I'm testing indoors with a vehicle connected and no GPS fix (or home location yet).  QGC seems to understand the local position ground altitude (as shown in the Mission Start), however, it is showing the mission plan as being completed below the terrain.

Also: does the RED flight path lines indicate a problem, in this case below terrain?

Screenshot:
![image](https://user-images.githubusercontent.com/12117027/101247845-45b58e80-36e1-11eb-8033-1023d98172a0.png)

another example
![image](https://user-images.githubusercontent.com/12117027/101247913-c5435d80-36e1-11eb-8619-443c8a093035.png)

**Comment by DonLakeFlyer** [comment] 2020-12-05 18:12
Yeah, something screwed up there. I thought I already had a 4.1 issue on it somewhere but can't find now. Can you attach the plan you are testing with.

The red line indicates below terrain.

**Comment by Antiheavy** [comment] 2020-12-05 18:36
>  Can you attach the plan you are testing with.

couple examples attached in this zip folder.
[below-ground-missions.zip](https://github.com/mavlink/qgroundcontrol/files/5647686/below-ground-missions.zip)

**Comment by moreba1** [comment] 2020-12-07 15:06
1- when we click on "SET TO MAP CENTER" button home altitude set to 0.
2- when we change location of Launch with mouse (home) , altitude of other relative waypoint does not changed .

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:08
> 1- when i click on "SET TO MAP CENTER" button home altitude set to 0. also in end of plan file altitude of "plannedHomePosition": is 0.
> 2- when i change location of Launch with mouse (home) , altitude of other relative waypoint does not changed .

Can you put these in a separate issue?

**Comment by moreba1** [comment] 2020-12-07 18:11
> 
> 
> > 1- when i click on "SET TO MAP CENTER" button home altitude set to 0. also in end of plan file altitude of "plannedHomePosition": is 0.
> > 2- when i change location of Launch with mouse (home) , altitude of other relative waypoint does not changed .
> 
> Can you put these in a separate issue?

these are reason of terrain altitude bar issue.

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:13
> these are reason of terrain altitude bar issue.

So far, not according to the plan files attached to this issue. They have good launch altitudes in them. I think this a separate issue, possibly related somehow but maybe not.

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:20
Wait I looked inside the plan file and the `"AMSLAltAboveTerrain": null` field is a NaN which is incorrect. So possible caused by 0 height launch position but not sure how a NaN would get in there. More likely caused by a save being allowed prior to terrain heights being downloaded. Still, there are multiple bugs here. Keeping them in separate issue is easier to track individual problems. Dragging a launch position and having it screw up the alt is a separate bug.

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:21
@antiheavy When you created these plans did you move the Launch Position?

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:23
> More likely caused by a save being allowed prior to terrain heights being downloaded.

Nope. This is a relative alt mission. Terrain isn't needed to save.

**Comment by DonLakeFlyer** [comment] 2020-12-07 18:36
@moreba1 Ok, digging further the plan file is incorrect in that it has a persisted alt of 0 for planned home. So it is likely only the dragging problem. Sorry going to fast and missed this part of your comment "also in end of plan file altitude of "plannedHomePosition": is 0."

**Comment by DonLakeFlyer** [comment] 2020-12-07 19:11
> I'm testing indoors with a vehicle connected and no GPS fix (or home location yet).

@Antiheavy I think there still might be a bug related to this specific test case. Can you retest after this current fix goes in?

**Comment by moreba1** [comment] 2020-12-07 21:31
maybe related to this change:
![image](https://user-images.githubusercontent.com/14200369/101406686-08265080-38ef-11eb-8d62-c298bb76b6ab.png)

**Comment by DonLakeFlyer** [comment] 2020-12-08 17:07
I'll reopen if the vehicle connected with no GPS causes problems. Looking at the code again I don't think so since the vehicle will not broadcast HOME_POSITION in that case.

**Comment by Antiheavy** [comment] 2020-12-09 05:50
Sorry for the delayed reply, yes I probably dragged the launch position. I often do that out of habit.

**Comment by Antiheavy** [comment] 2020-12-09 23:34
@DonLakeFlyer I;ve been testing today's daily and I cannot seem to repeat the same error.  Is this expected based on improvements you made?   However, I'm planning a mission over an area with rolling hills but I don't see any rolling hill terrain info display along the bottom bar:
![image](https://user-images.githubusercontent.com/12117027/101701587-d0312180-3a44-11eb-817f-b0e7286804c4.png)

**Comment by DonLakeFlyer** [comment] 2020-12-10 18:08
> I;ve been testing today's daily and I cannot seem to repeat the same error. Is this expected based on improvements you made?

Yes.

> However, I'm planning a mission over an area with rolling hills but I don't see any rolling hill terrain info display along the bottom bar:

Terrain data resolution is 1-arc second which is about 100 feet. So you might now see any deviation over small distances or small elevation change.

**Comment by Antiheavy** [comment] 2020-12-11 01:35
> Terrain data resolution is 1-arc second which is about 100 feet. So you might now see any deviation over small distances or small elevation change.

the golf course shown above has rolling hills all across it, maybe 150 feet vertical variation from lowest to highest spots across multiple hills.  

When I enable the follow terrain checkbox you can see that the hills are there, I would expect to see the "ground" line on the lower part of the altitude profile to show this same variation.  plus all the waypoints look crammed down at "0" altitude which also looks wrong/confusing.

![image](https://user-images.githubusercontent.com/12117027/101850096-b401b300-3b1e-11eb-8c62-0e1f88000ba2.png)

**Comment by DonLakeFlyer** [comment] 2020-12-11 16:36
Yup, screwed up. Can you attach that plan. I can use it for testing.

> plus all the waypoints look crammed down at "0" altitude which also looks wrong/confusing.

That's on purposed. The circular indicators don't track the height they stay on the bottom. This way you can see the flight path and terrain lines unobscured.

**Comment by Antiheavy** [comment] 2020-12-11 20:11
> Yup, screwed up. Can you attach that plan. I can use it for testing.

the mystery deepens:  i fired up QGC again to try to recreate and save a mission showing the issue, however, since my autopilot was still plugged into my PC it auto-connected and downloaded the onboard mission plan, which happens to be the same plan as shown above, but now it's all red lines and no terrain info.  screenshot and saved mission plan below:
![image](https://user-images.githubusercontent.com/12117027/101950220-8407ed80-3bba-11eb-98b4-2cd38ff9d9f1.png)
[mission plan downloaded off autopilot and now terrain and altitude looks weird.zip](https://github.com/mavlink/qgroundcontrol/files/5681416/mission.plan.downloaded.off.autopilot.and.now.terrain.and.altitude.looks.weird.zip)

**Comment by DonLakeFlyer** [comment] 2020-12-19 20:21
The plan files from the above comment will now load "better" with this last set of changes. FW Landing and Takeoff flight profiles are still not quite right.

**Comment by Antiheavy** [comment] 2020-12-19 22:32
here is a newly planned mission using today's daily.   Terrain follow enabled.  the ground elevation display seems scaled incorrectly or some other problem, it doesn't follow the mission undulations like you'd expect.  screenshot here and saved 
[mission and terrain undulations do not match.zip](https://github.com/mavlink/qgroundcontrol/files/5720226/mission.and.terrain.undulations.do.not.match.zip)
mission plan attached.
![image](https://user-images.githubusercontent.com/12117027/102700959-a54e8680-4217-11eb-80ae-c821e6a65f8f.png)

**Comment by DonLakeFlyer** [comment] 2020-12-19 23:46
That is because prior to #9265 the terrain profile min/max altitude calc was incorrect. Also the terrain profile was clipped to the min height of the chart display. So that flat lines of terrain are actually incorrect and are just being clipped at the bottom. The pull I just merged a few minutes ago should fix all this. Will take an hour or so for a new daily to pop out.

**Comment by Antiheavy** [comment] 2020-12-20 01:45
> merged a few minutes ago

oops!  I thought the version I was testing already had the fix.  I re tested with the newer daily and it's looking better (however, as you say, still something goofed with takeoff, it's showing red here):
![image](https://user-images.githubusercontent.com/12117027/102703300-b8bb1b00-4232-11eb-93a0-15d9789ae49c.png)

**Comment by moreba1** [comment] 2020-12-20 09:20
> Terrain data resolution is 1-arc second which is about 100 feet.

Can be displayed more resolution of terrain in takeoff and landing area?

**Comment by Antiheavy** [comment] 2020-12-20 15:06
> > Terrain data resolution is 1-arc second which is about 100 feet.
> 
> Can be displayed more resolution of terrain in takeoff and landing area?

The resolution of the source data is the limiting factor.  I suspect SRTM (Shuttle Radar Topography Mission) is the original source data which is about 1 arc-second (~30 meters), most elevation map providers use this is as their main layer since it was given to the world for free and has nearly full globe coverage.  https://en.wikipedia.org/wiki/Shuttle_Radar_Topography_Mission

**Comment by DonLakeFlyer** [comment] 2020-12-20 19:48
> Can be displayed more resolution of terrain in takeoff and landing area?

Don't quite understand what exactly you are asking for?

**Comment by DonLakeFlyer** [comment] 2020-12-30 18:23
This should be all fixed up now

**Closed by DonLakeFlyer** 2020-12-30 18:23 UTC
