### ISSUE TITLE
QGC won't open on any version past 3.0.2

### ISSUE THREAD

**Issue by kyle-irys** [mavlink/qgroundcontrol#6146] opened 2018-02-17 11:52 UTC
Windows 10 Home 32-bit 1709 16299.248
QGC 3.2.4 (Emlid Edge Custom Build 2.2, but relevant to anything 3.1.0 and above)
Emlid Edge v1.3

I am trying to get *ANY* version newer than 3.1.0 to run on my tablet (but specifically the Emlid version of 3.2.4) but I am having a major issue. Installation off all versions of QGC runs perfectly without error. The problem arises when launching the actual program. All versions 3.0.2 and older launch fine, anything 3.1.0 and newer does not launch at all. I get the spinning wheel cursor showing the computer is processing something, but no window/GUI loads at all. Compatibility/GPU Compatibility versions do not help.

I assume there must be some sort of *major* change between 3.0.2 and 3.1.0 but it isn't stated in the release docs so I have no idea if it is a compatibility issue. I bought this tablet specifically for field work and I have updated every drive imaginable.

Any help will be greatly appreciated.

**Comment by DonLakeFlyer** [comment] 2018-02-17 18:30
Duplicate of #6053

**Closed by DonLakeFlyer** 2018-02-17 18:30 UTC
