### ISSUE TITLE
Downloaded New Logs of PX4 v1.6.3 Are Unreadable in FlightPlot 0.3.1

### ISSUE THREAD

**Issue by rollysing** [mavlink/qgroundcontrol#5341] opened 2017-06-26 19:36 UTC
As recommended by @dagar to file this issue:

The logs are being downloaded as .PX4log instead of .ULG. The files directly from the SD Card are all .ULG and works fine with Flight Plot.

**Comment by DonLakeFlyer** [comment] 2017-06-26 21:05
Duplicate of https://github.com/mavlink/qgroundcontrol/issues/5305

**Closed by DonLakeFlyer** 2017-06-26 21:05 UTC
