### ISSUE TITLE
RTSP video not recording in Android.

### ISSUE THREAD

**Issue by RajanDhiman07** [mavlink/qgroundcontrol#10521] opened 2022-12-17 10:35 UTC
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. Andriod]
- QGC Version: stable 4.0
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by booo** [comment] 2022-12-28 14:32
Duplicate of https://github.com/mavlink/qgroundcontrol/issues/10366

**Closed by booo** 2022-12-28 14:32 UTC
