### ISSUE TITLE
Fix UDP packet drop in QGC

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3159] opened 2016-04-06 21:59 UTC
Assigned @DonLakeFlyer

**Comment by LorenzMeier** [comment] 2016-04-06 22:00
@sn0west the calibration issue might be very well related to this.

**Comment by NaterGator** [comment] 2016-04-07 02:07
Do we have evidence the OS is getting the packets and QGC is dropping them? I find that really hard to believe...

**Comment by DonLakeFlyer** [comment] 2016-04-07 02:21
I believe @dogmaphobic had verified a while ago (maybe in 5.4) . I'd mostly forgot about it though. There was a Qt Bug on readyRead signals getting lost with UDP. Seems like that was supposed to have been fixed though. So not sure if that is related or not.

It does need to be verified again though.

**Comment by NaterGator** [comment] 2016-04-07 02:44
Ok, can we scope this out a little (regarding which OS/UDP source users are reporting problems with)? I will test against a proxy in Windows but I am confident I did not see this before.

I have used Qt's UDP stack quite a bit and never had problems with packet loss @ the application on desktop operating systems.

**Comment by DonLakeFlyer** [comment] 2016-04-07 02:45
I've been trying to find some UDP test tool somewhere so I can connect to the port and see what's coming across. Should be easy to see from the raw data is the cal messages are there or not since they contain ascii.

**Comment by DonLakeFlyer** [comment] 2016-04-07 02:48
Basically the issue is QGC misses mavlink status text messages which drive the calibration state machine. So it misses a "side done" messages or an "orientation detected" message. The possible assumption is that UDP packets are getting dropped hence QGC doesn't see them.

@NaterGator Can you look at UDPLink to see if you see anything wrong with the implemenation. If you have some test tool to verify that text is coming through from the Vehicle on the port that would be great.
@dogmaphobic I assume you were seeing UDP drops on OSX? I'm OSX as well.
@sn0west What OS are you using?

**Comment by NaterGator** [comment] 2016-04-07 03:01
Got it... so particularly compass calibration statustext messages are causing issues. That narrows scope a bit. I will investigate... I've looked over the UDPLink implementation and it checks out as reasonable enough (despite the backwards legacy threading model Qt made so confusing... the "wrong" way works too). 

Maybe Linux / OSX thread scheduling is plaguing us here. We could see if upping the priority of the QThread that runs the socket's event loop helps?

**Comment by dogmaphobic** [comment] 2016-04-07 03:27
Yes, I've been meaning to get a session recorded using Wireshark but never got around to it. I will see if I get the time to put something together tomorrow.

https://www.wireshark.org

**Comment by Nyaruko** [comment] 2016-04-07 07:18
If I remeber it correctly, from qt5.4.2~ at least qt5.5, there was a bug on
readyRead signal emiting for UDPlink. So at that time, I thought you guys
changed the UDP link into a while loop using readBytes() and not using the
signal?

**Comment by NaterGator** [comment] 2016-04-07 14:23
@Nyaruko that's correct and was fixed in the version of Qt we're using: https://bugreports.qt.io/browse/QTBUG-46552

**Comment by DonLakeFlyer** [comment] 2016-04-07 17:55
> so particularly compass calibration statustext messages are causing issues.

That's one example. Gyro Cal can end up with the same problem as well.

**Comment by sn0west** [comment] 2016-04-07 18:23
@DonLakeFlyer OS X 10.10.5 (14F1713) and Kernel-Version:Darwin 14.5.0

**Comment by sn0west** [comment] 2016-04-07 18:45
Here are the Logs for the compass calibration. It still did not work. It seams that qgc always loos connection while calibrating.

[160407_Compass_Calibration_Problem_LOG_2.txt](https://github.com/mavlink/qgroundcontrol/files/209005/160407_Compass_Calibration_Problem_LOG_2.txt)

**Comment by sn0west** [comment] 2016-04-07 18:54
Gyro Calibration did not work as well. The box is green, but I get a error message after the calibration.

[160407_Gyro_Calibration_Problem_LOG_1.txt](https://github.com/mavlink/qgroundcontrol/files/209011/160407_Gyro_Calibration_Problem_LOG_1.txt)
![bildschirmfoto 2016-04-07 um 20 51 37](https://cloud.githubusercontent.com/assets/9918649/14363103/d775efa4-fd02-11e5-8dbc-21e4c3fe8ed2.png)

**Comment by sn0west** [comment] 2016-04-07 19:01
The ACC Calibration failed as well

[160407_ACC_Calibration_Problem_LOG_1.txt](https://github.com/mavlink/qgroundcontrol/files/209032/160407_ACC_Calibration_Problem_LOG_1.txt)

**Comment by sn0west** [comment] 2016-04-07 19:02
Btw each time I close the QGC window I get a error that it has not been closed propperly.
![bildschirmfoto 2016-04-07 um 21 00 52](https://cloud.githubusercontent.com/assets/9918649/14363330/f798f7c6-fd03-11e5-89a0-e43b3c7f42a2.png)

**Comment by DonLakeFlyer** [comment] 2016-04-10 02:22
@NaterGator Didn't you fix the close thing?

**Comment by NaterGator** [comment] 2016-04-10 02:24
Yep, after @sn0west and @shadow1runner reported it.

**Comment by NaterGator** [comment] 2016-04-10 02:28
I am still really troubled by _this_ bug. Nothing too out of the ordinary seems to be going on here, and back of the napkin math says PX4 stack isn't going to send more than about 600 bytes/second of these text messages. I just cannot believe Linux and OS X are choking on that paltry amount of data. 

Is this particularly happening with the ESP8266? Anyone not using it that is seeing the issue?

**Comment by DonLakeFlyer** [comment] 2016-04-10 02:30
As far as I can tell it a QT UDP problem. MAVProxy works fine over UDP without losing packets during mag cal.

**Comment by Nyaruko** [comment] 2016-04-10 03:49
May I know which os gotthis problem? Since I have test on windows and
android seems ok. Or how can I trigger this problem?

**Comment by DonLakeFlyer** [comment] 2016-04-10 04:12
You need to do a mag cal using a PixRacer over WiFi. I can repro on OSX and Android.

**Comment by Nyaruko** [comment] 2016-04-10 04:14
So normal pixhawk is fine? Only pix rapter? Then how can this be .a qt
problem?

**Comment by Nyaruko** [comment] 2016-04-10 04:15
I mean px racer

**Comment by DonLakeFlyer** [comment] 2016-04-10 04:22
It has to do with the WiFi UDP connection not the PixRacer really. I was just giving you some repro steps.

**Comment by NaterGator** [comment] 2016-04-11 14:50
@DonLakeFlyer I am just catching up here... I saw there was a patch to the MavESP8266 firmware to reduce the amount of buffering. Are issues still present and is the Qt side still implicated?

**Comment by dogmaphobic** [comment] 2016-04-11 15:26
> Are issues still present and is the Qt side still implicated?

As far as I can tell, no. I was able to see missing frames using Wireshark, which means the packets are being dropped before they reach QGC.

**Comment by DonLakeFlyer** [comment] 2016-05-30 02:40
@dogmaphobic There isn't anything to do on the QGC side here is there?

**Comment by dogmaphobic** [comment] 2016-05-30 02:51
> There isn't anything to do on the QGC side here is there?

Correct. As far as I know, all that can be done has been done both on the QGC side as well as on the ESP firmware. Current version has little to no loss under "normal" load.

**Closed** 2016-05-31 22:29 UTC
