### ISSUE TITLE
Feature request - Crop sprayer

### ISSUE THREAD

**Issue by mohammada315** [mavlink/qgroundcontrol#9639] opened 2021-05-12 06:02 UTC
![image](https://user-images.githubusercontent.com/29116372/117925983-4516c900-b30d-11eb-972d-6eca83c58bf5.png)
Is this supported?

**Comment by DonLakeFlyer** [comment] 2021-05-12 17:17
Nope

**Comment by mohammada315** [comment] 2021-05-12 17:55
@DonLakeFlyer  Will it be added in the future?

**Comment by DonLakeFlyer** [comment] 2021-05-14 17:27
No plans at this point

**Comment by HTRamsey** [comment] 2024-06-03 02:48
duplicate of #7263

**Closed by HTRamsey** 2024-06-03 02:48 UTC
