### ISSUE TITLE
QGC 4.1.1 video on macos is not working

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#9478] opened 2021-02-23 11:41 UTC
## Expected Behavior
Video should show

## Current Behavior
Video is not showing

## Steps to Reproduce:
1. Open QGC
2. Video does not show

## System Information
When posting bug reports, include the following information
- Operating System: MacOs 11.2.1
- QGC Version: 4.1.1
- QGC build: stable
- Flight Controller: None
- Autopilot (with version): None

## Log Files and Screenshots
It appears that the problem is that it can't find qmlglsink, from log:
```
 GST_ELEMENT_FACTORY gstelementfactory.c:456:GstElement *gst_element_factory_make(const gchar *, const gchar *): no such element factory "qmlglsink"!
```

**Comment by patrickelectric** [comment] 2021-02-24 11:04
The problem is with the .tar.gz used in deployment by trevis, I was able to fix it remotely, a new version will be provided to fix that.

**Comment by DonLakeFlyer** [comment] 2021-03-16 18:20
@patrickelectric What's going on here?

**Comment by patrickelectric** [comment] 2021-03-16 18:23
some dlls are missing on the gstreamer .tar.gz for macos, I'm planning to put some time and fix that tomorrow or Thursday

**Comment by DonLakeFlyer** [comment] 2021-03-27 17:58
Any updates on this. I'm going to mark a new stable today but this is still and outstanding stable problem.

**Comment by patrickelectric** [comment] 2021-03-27 23:54
There is a dmg with the fix, I'm waiting someone to do the test to me to make sure, but if someone here wants to try:
https://github.com/patrickelectric/qgroundcontrol/releases/tag/test-mac-video-fix

**Comment by DonLakeFlyer** [comment] 2021-03-28 15:33
Ah, ok thanks. You could ask on slck if anyone can test. I won't have time msyelf. I heading out of town for a couple weeks in about 5 minutes.

**Comment by smnogar** [comment] 2021-06-26 15:19
I can confirm that @patrickelectric's fix works on Big Sur. Can we get this fixed in the stable version :)

**Comment by ES-Alexander** [comment] 2021-10-13 22:22
Confirming this works for me and another person, both also on Big Sur 11.6.

> video does not work on daily nor stable 4.1.4

@patemil The fix is only in @patrickelectric's fork at the moment, so no surprises there. He's said he'll try to get back to this in the next week or two (and get it merged if nothing else needs fixing) :-)

**Comment by mrpollo** [comment] 2021-11-30 18:42
@patrickelectric did we ever manage to get this fixed? I can't recall

**Comment by Vaakefjell** [comment] 2022-01-14 10:18
I just had the same issue with the newest version of QGC (4.2.0) - has it not been fixed, or is there something related to my setup?

**Comment by patrickelectric** [comment] 2022-02-24 22:00
Check 4.1.6:
https://github.com/mavlink/qgroundcontrol/releases/tag/v4.1.6

**Comment by patrickelectric** [comment] 2022-02-24 22:00
4.2 will be the next one my list

**Comment by Vaakefjell** [comment] 2022-02-25 19:15
I just tested 4.1.6 and can confirm :)

**Comment by Vaakefjell** [comment] 2022-05-11 10:28
Any progress on adding the fix to the latest version?

**Comment by ES-Alexander** [comment] 2022-05-12 02:11
@Vaakefjell Patrick is away at the moment, and AFAIK hasn't had a chance to work on 4.2 yet.

Not sure if someone from outside Blue Robotics will have looked into it, although given #10140 perhaps the gstreamer version will be changing first. I'm unsure whether that's related to or will indirectly have an impact on the ease of fixing Mac video in `v4.2.x`.

**Closed** 2022-05-13 21:59 UTC
Labels: OSX, Video Streaming
