### ISSUE TITLE
Joystick Doesn’t Show Up Windows 10

### ISSUE THREAD

**Issue by vsobalski** [mavlink/qgroundcontrol#4450] opened 2017-01-17 18:50 UTC
Hi,

I have been using QGroundControl for a while, and have been experiencing an issue with the joystick over the last few versions. I can’t seem to find a way to display the controller's configuration window in QGroundControl even when I connect one or more joystick.
I tried a few different options with no luck, but recorded my stack trace.
Here is my configuration: 

- OS: Windows 10
- QGroundControl Version: HEAD:c17c1a6cc 2017-01-13 19:46:25 +0000
- Controllers used: Vjoy as well as BU0836A

- Stack trace using _DebugView --logging:JoystickLog_ available at the end of that message

I am setting up my joystick wrong?
Thanks a lot for your help,

Cheers,
Vincent

Stack Trace : 
`47	329.947075	4980	QGroundControl.exe	Settings location "C:/Users/aosl/AppData/Roaming/QGroundControl.org/QGroundControl.ini" Is writable?: true
48	329.963321	4980	QGroundControl.exe	Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\nJoystickLog.debug=true\n"
49	330.858358	4980	QGroundControl.exe	MAVLinkLogManagerLog: MAVLink logs directory: "C:/Users/aosl/AppData/Roaming/QGroundControl.org/QGroundControl/MAVLinkLogs"
50	330.925065	4980	QGroundControl.exe	JoystickLog: Available joysticks
51	330.925729	4980	QGroundControl.exe	JoystickLog: 	 "BU0836A Interface" axes: -1 buttons: -1 hats: -1 isGC: false
52	330.926222	4980	QGroundControl.exe	JoystickLog: _loadSettings  "BU0836A Interface"
53	330.926297	4980	QGroundControl.exe	JoystickLog: _loadSettings calibrated:throttlemode:exponential:deadband:badsettings false 0 false false false
54	330.926356	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 0 -1 true
55	330.926410	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 1 -1 true
56	330.926466	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 2 -1 true
57	330.926519	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 3 -1 true
58	330.971204	4980	QGroundControl.exe	JoystickLog: 	 "vJoy Device" axes: -1 buttons: -1 hats: -1 isGC: false
59	330.971695	4980	QGroundControl.exe	JoystickLog: _loadSettings  "vJoy Device"
60	330.971786	4980	QGroundControl.exe	JoystickLog: _loadSettings calibrated:throttlemode:exponential:deadband:badsettings false 0 false false false
61	330.971863	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 0 -1 true
62	330.971936	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 1 -1 true
63	330.972043	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 2 -1 true
64	330.972137	4980	QGroundControl.exe	JoystickLog: _loadSettings function:axis:badsettings 3 -1 true
65	331.328441	4980	QGroundControl.exe	Map Cache in: "C:/Users/aosl/AppData/Local/cache/QGCMapCache300" / "qgcMapCache.db"
66	332.585228	4980	QGroundControl.exe	Orphaned log file count 0
67	332.705641	4980	QGroundControl.exe	LinkManager mavlinkStatus:channel:flags 0x15410fc 1 2
68	343.353681	4980	QGroundControl.exe	qrc:qml/GeneralSettings.qml:37: ReferenceError: offlineVehicleCombo is not defined
69	343.353796	4980	QGroundControl.exe	qrc:qml/GeneralSettings.qml:38: ReferenceError: offlineVehicleCombo is not defined
70	414.979637	4980	QGroundControl.exe	LinkManager mavlinkStatus:channel:flags 0x1541118 2 2
71	415.588169	4980	QGroundControl.exe	Temp log "C:/Users/aosl/AppData/Local/Temp/FlightData453591.mavlink"
72	418.616970	4980	QGroundControl.exe	Vehicle::_sendMavCommandAgain retrying command:_mavCommandRetryCount 520 2
73	421.617302	4980	QGroundControl.exe	Vehicle::_sendMavCommandAgain retrying command:_mavCommandRetryCount 520 3
74	424.614556	4980	QGroundControl.exe	Vehicle::_sendMavCommandAgain retrying command:_mavCommandRetryCount 520 4
`

**Comment by NaterGator** [comment] 2017-01-17 21:53
Thanks for your report! This issue is being worked on.

Duplicate of #4442

**Closed by NaterGator** 2017-01-17 21:53 UTC
