### ISSUE TITLE
Figure out how to make toolbar transparent again with correct colors

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3190] opened 2016-04-11 01:29 UTC

**Comment by dogmaphobic** [comment] 2016-04-17 19:11
Assigning to me as I had already done some of the work and have it stashed.

**Comment by DonLakeFlyer** [comment] 2016-04-18 00:25
Can you put the child controls parented to an Item which is sized correctly, so we don't have to pass around the available height thing? This will also make the right side dialogs work better.

**Comment by dogmaphobic** [comment] 2016-04-18 00:35
The was my first approach/attempt. The issue is that you need a QGCView way down below and FlightDisplayView is the QGCView. The map/video display has to be "fill parent". The Flight Widget within FlightDisplayView is properly sized and it should be the parent from which you get the height but ValuesWidget uses parent.parent.parent.qgcView to get the size. At that point my head was spinning and I gave up :)

**Comment by DonLakeFlyer** [comment] 2016-04-19 22:29
This whole parent/child chain needs a roto-tilling. But not till after 3.0. Let me see what I can do.

**Comment by dogmaphobic** [comment] 2016-04-22 13:19
Done.

**Closed by dogmaphobic** 2016-04-22 13:19 UTC
