### ISSUE TITLE
QGC daily build 04/05/2018 unable to display full user interface

### ISSUE THREAD

**Issue by r0gelion** [mavlink/qgroundcontrol#6318] opened 2018-04-06 20:08 UTC
Trying to configure Intel Aero Ready to Fly Drone, using QGC daily build (e15f496ab) and got the next error:

![qgc_daily_params_error](https://user-images.githubusercontent.com/5013954/38441825-e25be136-399a-11e8-803d-2f3275452ee1.PNG)

Intel Aero drone is running PX4 firmware and here are more information about the software/firmware it uses:

BIOS_VERSION = Aero-01.00.16
OS_VERSION = Poky Aero (Intel Aero Linux Distro) 1.6.1 (pyro)"
AIRMAP_VERSION = 1.8
FPGA_VERSION = 0xc2
AeroFC firmware version = 1.7.4

QGC daily build (e15f496ab) in Windows 10.

I checked the stable version of QGC v3.3.1 and the full user interface was displayed and I was able to configure the drone, just got an error when the drone connected to QGC.

![qgc_shutdown_not_supported](https://user-images.githubusercontent.com/5013954/38441986-81c72ef6-399b-11e8-90bc-730ac7ae3009.PNG)

@DonLakeFlyer @dagar

**Comment by DonLakeFlyer** [comment] 2018-04-06 20:12
That's all firmware side and/or vehicle setup issues. I'd post there.

**Comment by juvinski** [comment] 2018-04-06 20:58
I had this error too, in the QT log windows there is several Error writing to QHostAddress("")

**Comment by DonLakeFlyer** [comment] 2018-04-06 21:04
Wait your daily is based off of a bad pull. First thing use a newer daily.

**Comment by r0gelion** [comment] 2018-04-06 21:32
> That's all firmware side and/or vehicle setup issues. I'd post there.

Thank you! I'll post this there.

**Comment by DonLakeFlyer** [comment] 2018-04-06 22:39
> Wait your daily is based off of a bad pull. First thing use a newer daily.

Try with newer daily build first to see if things work better. The specific one you are using has a bad bug in it.

**Comment by juvinski** [comment] 2018-04-06 23:32
I tried with last master - commit 189dc1cf115302215125537b1fdbf976e42f2ca8
and ardusim - with plane - and error still happening.

**Comment by DonLakeFlyer** [comment] 2018-04-07 01:07
Ok. Then not caused by that bad pull.

**Comment by Antiheavy** [comment] 2018-04-15 18:13
this error pops up for me all the time now in SITL using PX4 Master and recent QGC Dailies - seems like the UDP connection is dropping out or something, not sure:
![image](https://user-images.githubusercontent.com/12117027/38781687-ab392a4a-40ae-11e8-820c-ba24d5c515e4.png)

**Comment by DonLakeFlyer** [comment] 2018-04-30 23:03
UDP problems are fixed now

**Closed by DonLakeFlyer** 2018-04-30 23:03 UTC
