### ISSUE TITLE
QGC Crash while entering Flight Mode Tab if RC is on!

### ISSUE THREAD

**Issue by sn0west** [mavlink/qgroundcontrol#3262] opened 2016-04-22 20:48 UTC
Daily QGC crash if I try to enter the Flight Modes tab while my RC is on. If the RC is off then I can enter this tab. 
If I flash the apm stack QGC dosen't crash.

I have a Mac osx 10.10.5 and flashed the latest px4 master.

App Logg over Terminal
[160422_QGC_Crash_FM.txt](https://github.com/mavlink/qgroundcontrol/files/232520/160422_QGC_Crash_FM.txt)

Syslog
[160422_QGC_Crash_SystemLog.txt](https://github.com/mavlink/qgroundcontrol/files/232521/160422_QGC_Crash_SystemLog.txt)

Do not work
![bildschirmfoto 2016-04-22 um 22 17 44](https://cloud.githubusercontent.com/assets/9918649/14754383/562b198a-08db-11e6-8744-be14b3f5e4ed.png)

**Comment by jcooper21** [comment] 2016-04-22 22:08
I have the same issue and was just about to post it. I have PX4 beta build from today on the pixhawk.

**Comment by jcooper21** [comment] 2016-04-23 01:05
The issue is if you click on the flight mode tab before all the sensors are calibrated, then it crashes.  It works if you calibrate everything first.  Hopefully they can fix the bugs.

**Comment by dogmaphobic** [comment] 2016-04-23 01:06
I could not reproduce it. It took a bit because I had no system using a "normal" radio setup. To make sure, I put together a frame using an X8R Receiver and a Taranis Radio. Flashed the Pixhawk with PX4 Master, went through all the frame setup and calibration and proceeded to go into the flight modes panel and set a couple of channels just fine.

![screen shot 2016-04-22 at 8 59 21 pm](https://cloud.githubusercontent.com/assets/749243/14758338/937fb740-08cd-11e6-9b11-4b401e332065.png)

What exactly is your setup like?

@jcooper21  *Windows 10*, *PX4 beta build* and *you cannot setup an airframe* are not exactly what this issue is about. If you have a better description of your problem, could you please enter a new issue for it?

**Comment by dogmaphobic** [comment] 2016-04-23 01:06
Ha! missed you by less than a second it seems. Yes, I did go through the calibration first.

**Comment by dogmaphobic** [comment] 2016-04-23 01:08
Alright, let me reset the Pixhawk to nothing and start over.

**Comment by dogmaphobic** [comment] 2016-04-23 02:13
The crash is in this line:

https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc#L58

It makes a call into `Fact::rawValue()` without checking to see if `getParameterFact()` returned a valid `Fact` or not. `getParameterFact()` is returning NULL and thus the crash. I can make a work around but this is @DonLakeFlyer 's domain so only he will be able to get to the root of the problem. 

Something is not being initialized until you calibrate the vehicle. What I will do is prevent you from going into the *Flight Modes* panel before calibration (and putting a NULL pointer check above just in case).

**Comment by jcooper21** [comment] 2016-04-23 02:27
Thanks for the quick fix

**Comment by dogmaphobic** [comment] 2016-04-23 03:02
The (possibly temporary) fix is in #3264. In the mean time, make sure to run the calibration prior to going into the Flight Modes panel. @jcooper21, thanks for the calibration sequence hint. It would take me forever to find this without it.

**Comment by sn0west** [comment] 2016-04-23 09:20
would it be more intuitive to change the setup order? I had to first choos a frame, then went to the second red point Radio, did  the calibration, wenn to the next red point FM and then crashed. 
In Mission Planner you have the mandatory tab witch you should go from top to bottom.

**Comment by DonLakeFlyer** [comment] 2016-04-26 01:44
I think there may be a hole somewhere in the switch between simple/advanced flight modes which leaves FLT_MODE set strangely. Which then causes the RC#_REV parameter to be the wrong name. Also likely holes with respect to user setting FLT_MODE parameter manually to something bogus.

**Comment by DonLakeFlyer** [comment] 2016-05-30 02:11
@sn0west  @jcooper21 Is this still a problem with latest daily?

**Comment by jcooper21** [comment] 2016-05-30 02:23
Not sure. I won't be able to test much for a couple weeks.

**Comment by DonLakeFlyer** [comment] 2016-06-14 02:40
I believe this is fixed now

**Closed by DonLakeFlyer** 2016-06-14 02:40 UTC
