### ISSUE TITLE
QT 5.10 maps still broken

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5916] opened 2017-12-27 23:18 UTC
- Ground station operating system. - OSX 10.13.2
- QGroundControl version and build (daily, stable, self-built from source, etc.)-Master (2017-12-27)
- Autopilot board: Pixhawk I, Pixhawk Mini, Pixhawk 2, etc. - N/A
- Autopilot firmware (e.g. PX4, ArduPilot, custom) and version. - N/A
- Exact steps to reproduce the problem. Starting from booting QGroundControl to when the problem occurs.

Maps are unusable. Only able to see the globe image, no Zoom available

Building with QT 5.10 after seeing the PR that corrected the compilation errors on 5.10, now it compiles ok but where we can see maps the maps are frozen and unusable.

Building with QT 5.9.3 no issues.

**Comment by dogmaphobic** [comment] 2017-12-28 00:28
I have not had a chance to test this since the PR was created/merged. I will take a look at it tomorrow...

**Comment by dogmaphobic** [comment] 2017-12-28 20:36
Something is out of whack but I can readily see what is going on. Bing maps are working fine but Google maps don't even try to load. I won't have the time to look further into this in a while.

@patrickelectric Did you test all map providers with your PR?

**Comment by patrickelectric** [comment] 2017-12-29 01:16
Ok.. I can reproduce the problem..
Work with:
- [ ] Bing
- [ ] Google
- [ ] Statkart
- [ ] Eniro
![image](https://user-images.githubusercontent.com/1215497/34427087-26af4648-ec25-11e7-8c02-5f66c964487e.png)

**Comment by patrickelectric** [comment] 2017-12-29 01:29
The problem appears to be only with google, I'll try to solve this.

**Comment by patrickelectric** [comment] 2017-12-29 02:44
@dogmaphobic, it appears to be something related to the TileCache.
Take a look [here](https://paste.kde.org/pjusvwon8), any idea ?
It doesn't call QGeoTileFetch or anything related.

**Comment by patrickelectric** [comment] 2017-12-29 13:03
Solved, I'll send a PR asap.

**Closed** 2018-01-05 18:29 UTC
