### ISSUE TITLE
Problem with log download from Pixhawk (Reproducible)

### ISSUE THREAD

**Issue by samacumen** [mavlink/qgroundcontrol#5610] opened 2017-08-28 12:10 UTC
**Summary:** Unable to download logs via QGC connected to Pixhawk beyond 5th attempt (over USB)
**Firmware:** Stable v3.2.2 QGC, v1.6.5 Stable Release PX4, Ubuntu 16.04LTS 

**Steps to reproduce:**
1) Open the "Log Download" tab in QGC
2) Press 'Refresh' button - brings the list of logs
3) Download any log (choose a small size so that its faster to reproduce the issue)
4) Wait until 'Downloaded' state
5) Repeat steps 2), 3) and 4)  judiciously,at least 5 times.

On the 5th trial, on pressing the 'Refresh' button "no logs are obtained" from PX4.

**What I expect on pressing a "Refresh":**

![image](https://user-images.githubusercontent.com/1699546/29772393-e2914bc8-8bf8-11e7-96a9-ce6ad92613eb.png)

**But this is what I eventually get on pressing the "Refresh" (No Logs obtained):**

![image](https://user-images.githubusercontent.com/1699546/29772706-34f52708-8bfa-11e7-8920-471b1d80f9bd.png)

This issue is very much reproducible at my end when I have attempted the above steps "as is". I am not certain if this is a Pixhawk or a QGC issue. My suspect is that the state in PX4 goes into a wrong state during these operations. Since this is observed at the QGC side, I am reporting the issue here.

Request your observation: @LorenzMeier , @dogmaphobic

**Comment by samacumen** [comment] 2017-08-28 12:41
**Another issue I found with log download is:**

If the "Status" of a log goes into "error" (because a log file was corrupt in the Pixhawk's SD card), Pixhawk needs to be rebooted to show up the list of logs again for download. If an error occured for a log download, I would expect to be able to request the list of logs for download, anyways.

**See the first line below, press "Refresh" after error, nothing shows up again. Requires Pixhawk reboot:**

![image](https://user-images.githubusercontent.com/1699546/29773617-927e4e6e-8bfe-11e7-9b40-770642a16073.png)

**Comment by samacumen** [comment] 2017-09-22 21:47
Is this being addressed and any idea if it could be resolved for the next release? Thanks.

**Comment by DonLakeFlyer** [comment] 2017-09-25 16:37
@bkueng Is this different from what you fixed?

**Comment by bkueng** [comment] 2017-09-26 09:41
Yes, these look like different issues

**Comment by DonLakeFlyer** [comment] 2017-09-26 15:58
@bkueng Could you take a look at this one then as well? Seems a bit similar to changes you already made. I assume this is QGC side as opposed to Firmware side. but maybe not?

**Comment by bkueng** [comment] 2017-09-28 08:42
Ok, I'll try to reproduce

**Comment by bkueng** [comment] 2017-10-02 12:59
First issue: I tried more than 10 times on QGC master, PX4 master on a Pixracer via USB, but never had an issue.

Second issue: should be fixed in https://github.com/mavlink/qgroundcontrol/pull/5722

**Comment by samacumen** [comment] 2017-10-02 13:12
@bkueng First issue is probably more concerning. I just tried it again this morning and it is very much reproducible at my end (as given from Steps (1) to (5) ), following it as is. After downloading a log, you need to click 'Refresh' and it should reproduce on 6th cyclic attempt, i.e. receive nothing from the Pixhawk (running PX4 master).

Let me know if you need more information in order to reproduce this.

Thanks.

**Comment by AlexisTM** [comment] 2017-10-06 12:03
I had to delete all logs (465) and refly and it downloaded the log.

QGC was spamming: Received log data for wrong log

**Comment by bellahduan** [comment] 2017-10-10 14:05
@samacumen hi , the log download from QGC is **.px4log , but it can not use to analysis.  how to solve the problem?

**Comment by DonLakeFlyer** [comment] 2017-10-20 18:18
@bkueng Ok, to close this issue now?

**Comment by bkueng** [comment] 2017-10-21 05:43
No, according to @samacumen there's one more issue (which I'm unable to reproduce):

> Unable to download logs via QGC connected to Pixhawk beyond 5th attempt (over USB)
>
> Steps to reproduce:
>
>   - Open the "Log Download" tab in QGC
>   - Press 'Refresh' button - brings the list of logs
>   - Download any log (choose a small size so that its faster to reproduce the issue)
>   - Wait until 'Downloaded' state
>   - Repeat steps 2), 3) and 4) judiciously,at least 5 times.
>
> On the 5th trial, on pressing the 'Refresh' button "no logs are obtained" from PX4.

**Comment by fkaiser** [comment] 2017-10-23 09:28
Observed similar issue as described by @samacumen. The problem seems to lie on the PX4 side with this message showing up as the debug output from autopilot:

[mavlink] MavlinkLogHandler:: init Error creating /fs/microsd/$log$.txt

Message stems from this line in [PX4 code](https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_log_handler.cpp#L467).

In that case there seems to an issue with the file handling. Only remedy is to reboot autopilot.

**Comment by samacumen** [comment] 2017-10-23 09:32
@fkaiser Thanks for helping reproduce the issue. You probably hit the birds eye! I was also quite sure in my analysis of the issue being on PX4 side as I found the QGC side clean since it only acts on the received mavlink messages from PX4. At certain (repeated) point of action, QGC stops receiving.

Should we transfer this to the PX4 team? @LorenzMeier

**Comment by DonLakeFlyer** [comment] 2017-10-23 15:07
> Should we transfer this to the PX4 team?

@bkueng Any comments on this?

**Comment by bkueng** [comment] 2017-10-23 15:28
Hmm, the error handling on the Firmware looks correct to me. It seems to be an underlying issue in the file system or NuttX or not enough file descriptors. And QGC then reacts correctly showing an empty list. So yes we can move it over, but I'm not sure if it helps.

@samacumen @fkaiser if you're in a position to recompile, can you exchange https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_log_handler.cpp#L467 with:
```
PX4LOG_WARN("MavlinkLogHandler::init Error creating %i %s\n", errno, kTmpData);
```
And see what the output is?
If it's a file descriptor limit, it's resolved on PX4 master - which seems to me the most likely cause.

**Comment by bkueng** [comment] 2017-10-23 15:49
Just came across another bug: https://github.com/mavlink/qgroundcontrol/pull/5778

**Comment by samacumen** [comment] 2017-10-23 16:06
@bkueng Thanks for your analysis and taking notice of these issues. As a user of the system, I could reproduce it and don't mind if qgc or px4 side fixes it as appropriate.

I'll be back to work in a couple days and will compile what you suggest and report back with the result.

**Comment by samacumen** [comment] 2017-10-27 14:37
I am unable to reproduce the issue reported with the steps I initially wrote, not sure if it has been fixed in the interim. I used the latest PX4 master and latest qgc_master branches as of today.

@fkaiser you said you managed to reproduce this issue, which branch did you reproduce this problem on?

**Comment by fkaiser** [comment] 2017-10-30 12:16
I think it was stable v1.5.5 on the PX4 side.

**Comment by DonLakeFlyer** [comment] 2017-12-30 02:07
The combination of QGC and Firmware fixes should have taken care of this

**Closed by DonLakeFlyer** 2017-12-30 02:07 UTC
