### ISSUE TITLE
Camera_capture msg type mismatch

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#7616] opened 2019-07-24 08:50 UTC
PX4 camera_capture uorb message has a timestamp field declared as a uint64 timestamp.
QGC instead save the imported data inside a structure GeoTagWorker::cameraFeedbackPacket with field timestamp declared as double.
This lead to a mismatch between the saved uorb data and the QGC imported one. 
This is a bug. isn't it?

**Comment by DonLakeFlyer** [comment] 2019-07-24 16:31
The values stored in those two fields are in seconds translated from the log values, hence double. That seems fine to me?

**Comment by FlavioTonelli** [comment] 2019-07-24 17:17
I can't get your point. Neverless of the unit of measure we are implicitly converting a uint64 variable into a double. Isn't it wrong?
The log value and the QGC does not match.(See screenshot) 
Am I missing something?
<img width="1276" alt="Schermata 2019-07-24 alle 19 12 17" src="https://user-images.githubusercontent.com/9391950/61814071-88a5f780-ae47-11e9-9453-f47280ad1968.png">

**Comment by DonLakeFlyer** [comment] 2019-07-24 17:21
> The log value and the QGC does not match

I understand that. But as far as I understand the cameraFeedbackPacket data structure in QGC is only used internally to QGC. Why do they need to match?

**Comment by DonLakeFlyer** [comment] 2019-07-24 17:25
They don't match from a data structure standpoint. But they do match from a semantic standpoint as far as representing the same amount of time with the internal QGC value being representing in floating point seconds.

**Comment by FlavioTonelli** [comment] 2019-07-24 17:47
Ok now I get how was it is suppose to work.
Yes they both represent time you are right. What you lose is a 1 to 1 connection with the drone log and you probably lose some time accuracy.
Which are the Pro of such approach?

**Comment by DonLakeFlyer** [comment] 2019-07-24 17:50
> Which are the Pro of such approach?

No idea. You would have to ask @birchera who wrote that code.

**Comment by birchera** [comment] 2019-07-24 18:09
As far as I can see the cameraFeedbackPacket were introduced 2 years ago by @mhkabir, maybe he can answer your question.

**Comment by DonLakeFlyer** [comment] 2019-07-25 16:44
Discussion can continue, but I'm closing issue since it's not a bug.

**Closed by DonLakeFlyer** 2019-07-25 16:44 UTC
