### ISSUE TITLE
gstreamer problem

### ISSUE THREAD

**Issue by MilanBacaCz** [mavlink/qgroundcontrol#10735] opened 2023-07-15 18:42 UTC
Hi all,

i have a problem with deployment on MacOs.

I have gstreamer installed according manual, but the process wants to find it in wrong location.

Post Link Common
macdeployqt
ERROR: no file at "/Library/lib/GStreamer.framework/Versions/1.0/lib"

Right location should be  "/Library/Frameworks/GStreamer.framework/Versions/1.0/lib" where the files actually are.

Could someone help?

**Comment by zdanek** [comment] 2023-12-19 17:24
Duplicate of #10312

**Closed** 2024-05-31 04:49 UTC
