### ISSUE TITLE
QGroundCOntrol build Failed

### ISSUE THREAD

**Issue by SebastianViollaz** [mavlink/qgroundcontrol#10568] opened 2023-02-10 17:00 UTC
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Succesfull build in QT
## Current Behavior
Build Error iin qt

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 22.04.1
- QGC Version: Last in GitHub
- QGC build: FronSource

## Detailed Description
I try to open de .pro file in QT Creator, when i try to build this error show up. The path is not an existing one

/qgroundcontrol/libs/libevents/libevents/libs/cpp/parse/parser.h:13: error: nlohmann_json/include/nlohmann/json_fwd.hpp: No such file or directory
In file included from /qgroundcontrol/libs/libevents/libevents/libs/cpp/parse/parser.cpp:1:
/qgroundcontrol/libs/libevents/libevents/libs/cpp/parse/parser.h:13:10: fatal error: nlohmann_json/include/nlohmann/json_fwd.hpp: No such file or directory
   13 | #include "nlohmann_json/include/nlohmann/json_fwd.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Log Files and Screenshots
![image](https://user-images.githubusercontent.com/85691148/218151130-f74d8ff7-7922-4f34-83e9-2a6b1b15702b.png)

**Comment by TheLastImperial** [comment] 2023-02-12 06:10
In my case the `nlohmann_json` of `libevents` was not there. I just go to `libs/libevents/libevents` and run:

```bash
git submodule init
git submodule update
```

**Comment by urmyfaith** [comment] 2023-02-12 09:59
> In my case the submodule `nlohmann_json` of `libevents` was not there. I just go to `libs/libevents/libevents` and run:
> 
> ```shell
> git submodule init
> git submodule update
> ```

nice

**Comment by booo** [comment] 2023-02-14 08:38
Please provide us with the exact steps to reproduce the problem.

Please check the documentation for a howto.

**Comment by SebastianViollaz** [comment] 2023-02-14 12:32
> In my case the submodule `nlohmann_json` of `libevents` was not there. I just go to `libs/libevents/libevents` and run:
> 
> ```shell
> git submodule init
> git submodule update
> ```

this solve the problem for me

**Comment by booo** [comment] 2023-02-14 12:51
Ok. I close this. Seems to be human error ;)

**Closed by booo** 2023-02-14 12:51 UTC
Labels: Bug
