### ISSUE TITLE
[FR] additional axes at joystic

### ISSUE THREAD

**Issue by whoim2** [mavlink/qgroundcontrol#10628] opened 2023-03-19 20:51 UTC
Im use custom joystick with sticks, pots and 3-way switchs as axes. But used only 4-ch of sticks, i not may attack my axes to raw channels, as in MP.

**Comment by HTRamsey** [comment] 2024-11-30 23:52
duplicate of #10632

**Closed by HTRamsey** 2024-11-30 23:52 UTC
Labels: Feature Request
