### ISSUE TITLE
parameter editing issues on PixRacer

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#3163] opened 2016-04-07 19:44 UTC
setting parameters is flaky: changing MC_ROLLRATE_P works properly, but changing MC_PITCHRATE_P has no effect. (USB connection)

On Nexus 7 tablet, QGC does not connect to PixRacer wifi; parameters never load

**Comment by NaterGator** [comment] 2016-04-07 19:53
The wifi issue on N7 is likely related to this: https://github.com/mavlink/qgroundcontrol/issues/3128#issuecomment-205525165

**Comment by LorenzMeier** [comment] 2016-04-09 18:30
@kd0aij I can't reproduce this on a Samsung Tab 4.

**Comment by kd0aij** [comment] 2016-04-09 20:37
something is different in the newLogger branch, I'll see if the fmuv4 startup is wrong.

**Comment by kd0aij** [comment] 2016-04-09 20:42
Sorry, "senior moment" :)
I commented out the mavlink startup on wifi because I was short of flash. It might work better if mavlink is running on the port.

**Comment by DonLakeFlyer** [comment] 2016-04-09 20:44
@kd0aij Ok, to close this then right?

**Comment by kd0aij** [comment] 2016-04-09 20:46
still have the problem with setting parameters over USB

**Comment by LorenzMeier** [comment] 2016-04-09 21:10
Can you please reset your params via QGC, flash master via QGC and format your SD card and then exactly tell us what you are doing which doesn't work? None of what you report is reproducible for me so far.

**Comment by kd0aij** [comment] 2016-04-09 21:18
I can't reproduce the parameter setting problem either now. Must have been a flaky USB connection.
Will close this issue and henceforth be sure to listen for the confirmation tone on parameter changes.

**Comment by DonLakeFlyer** [comment] 2016-04-09 22:32
I'm reopening this because I thought QHC would report if a parameter write failed. Turns out it doesn't. I'll fix that.

**Comment by kd0aij** [comment] 2016-04-09 23:13
@DonLakeFlyer I don't know if it means anything, but yesterday this problem seemed reproducible:
"changing MC_ROLLRATE_P works properly, but changing MC_PITCHRATE_P has no effect"
Hard to believe unless the length of the name string is a factor.

**Comment by DonLakeFlyer** [comment] 2016-04-09 23:16
If it was the max param name length (16) then I'd wonder but it isn't. So strangeness.

**Comment by DonLakeFlyer** [comment] 2016-04-09 23:33
Ok. So QGC will notify now. So hopefully it will help us track down if there is something going wrong here.

**Closed by DonLakeFlyer** 2016-04-09 23:33 UTC
